Support T-SQL sp_helplinkedsrvlogin stored procedure
babelfish-for-postgresql/babelfish_extensions pull request #1081
Opened 2023-01-18 05:21 UTC by basasairohan

### Description

This commit adds support for sp_helplinkedsrvlogin stored procedure.
sp_helplinkedsrvlogin has been implemented such that internally it uses sys.linked_logins and sys.servers views.

Signed-off-by: Sai Rohan Basa [bsrohan@amazon.com](mailto:bsrohan@amazon.com)

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** N/A

* **Arbitrary inputs -** Yes

* **Negative test cases -** Yes

* **Minor version upgrade tests -** N/A

* **Major version upgrade tests -** N/A

* **Performance tests -** N/A

* **Tooling impact -** Yes

* **Client tests -** Yes

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-26 12:15 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +GRANT EXECUTE ON PROCEDURE sys.sp_helplinkedsrvlogin TO PUBLIC;
The procedure should error out if there does not exist an entry with the mentioned @rmtsrvname. In this implementation we will return 0 rows if that happens

2023-01-26 12:25 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +    		s.name AS linked_server,
column names are incorrect. Please fix them to match T-SQL definition

2023-01-26 12:26 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +    		s.name AS linked_server,
Eg. it should be Linked Server and not linked_server

2023-01-26 12:36 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +END;
We can club all the if..else conditions. Declare two variables server_id and local_principal_id and they both are NULL if no id exists for the passed arguments. We can then rewrite the WHERE clause like WHERE (@server_id is NULL or @server_id = s.server_id) AND (@local_principal_id is NULL or @local_principal_id = l.local_principal_id)

2023-02-02 03:54 UTC, Deepesh125 requested changes

2023-02-02 03:54 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +					RETURN 0;
as per t-sql doc, return code should be 1 in case of failure.

2023-02-02 03:54 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +			SELECT @local_principal_id = usesysid FROM pg_user WHERE usename = @locallogin;
Default collation of usename is 950 which will do case sensitive comparison. Please add `COLLATE sys.database_default` or case left hand side operator to sysname here and add case insensitive test cases on locallogin param,

2023-02-02 08:49 UTC, Deepesh125 approved these changes

2023-02-02 08:52 UTC, merged