Support T-SQL sp_linkedservers stored procedure
babelfish-for-postgresql/babelfish_extensions pull request #1088
Opened 2023-01-19 09:02 UTC by basasairohan

### Description

This commit adds support for sp_linkedservers stored procedure.
sp_linkedservers has been implemented such that internally it uses sys.servers view.

Signed-off-by: Sai Rohan Basa [bsrohan@amazon.com](mailto:bsrohan@amazon.com)

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** N/A

* **Arbitrary inputs -** N/A

* **Negative test cases -** N/A

* **Minor version upgrade tests -** N/A

* **Major version upgrade tests -** N/A

* **Performance tests -** N/A

* **Tooling impact -** Yes

* **Client tests -** Yes

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-26 12:18 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +GRANT EXECUTE ON PROCEDURE sys.sp_linkedservers TO PUBLIC;
no newline

2023-01-26 12:18 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +		provider_string AS SRV_PROVIDERSTRING,
fix indentation

2023-01-26 12:20 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +		provider_string AS SRV_PROVIDERSTRING,
fix indentation

2023-01-26 12:21 UTC, thephantomthief commented on test/JDBC/input/linked_servers-vu-verify.sql
> +GO
add a new line at EOF

2023-01-26 12:39 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +    	name AS SRV_NAME,
I think case would not be persisted. You will have to enclose the column names in quotes

2023-01-30 09:07 UTC, thephantomthief submitted a review, later dismissed

2023-01-30 14:32 UTC, Deepesh125 requested changes

2023-01-30 14:32 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +		provider AS "SRV_PROVIDERNAME",
sys.servers. provider is of sys.sysname but we need to return nvarchar(128). Same is true for SRV_PRODUCT

2023-01-31 09:08 UTC, Deepesh125 approved these changes

2023-01-31 09:10 UTC, merged