Test file for pg_stat_statements_tsql
babelfish-for-postgresql/babelfish_extensions pull request #1381
Opened 2023-03-31 09:14 UTC by kritika-0601

This commit tests working of pg_stat_statements from T-SQL endpoint.
Tested all the DDLs, DMLs, TCLs, aggregate functions, constraints etc.

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-12 08:02 UTC, HarshLunagariya commented on test/JDBC/input/pg_stat_statements_tsql.mix
> +-- simple and compound statements
Add testcases for:
create/alter/drop type
alter/drop object
rollback/save transaction

2023-06-14 08:18 UTC, HarshLunagariya requested changes

2023-06-14 08:18 UTC, HarshLunagariya commented on test/JDBC/input/pg_stat_statements_tsql.mix
> +-- simple and compound statements
We are still missing ALTER object statements.

2023-06-22 18:06 UTC, HarshLunagariya approved these changes

2023-06-26 05:55 UTC, shardgupta approved these changes

2023-06-26 05:56 UTC, merged