Create proc/func/database etc not visible in pg_stat_statements view
babelfish-for-postgresql/babelfish_extensions pull request #1424
Opened 2023-04-13 10:06 UTC by kritika-0601

Currently Babelfish does not show statements like create proc/func/database, drop database etc inside the pg_stat_statements table. After my change now it will be visible in the view.
pg_stat_statements displays planning and execution statistics for all SQL statements executed by a server. Some of the statements are not being tracked by it. Mainly because subsequent processutility hooks after bbf_processutilty are not being called, what happens is inside bbf_processUtility, babelfish specific function is called and it does not trigger the subsequent hooks due to which query statistics are not being stored in the table.
Created a hook for that and called it inside relevant ProcessUtility function.

Link for engine PR: https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/pull/127

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-18 10:29 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/hooks.c
> +			CreateFunctionStmt *stmt = (CreateFunctionStmt *)parsetree;
add implementation for create function into a separate utility function

2023-04-18 10:29 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/hooks.h
> +extern void PLTsqlProcessTransaction(Node *parsetree,
this should not be in hooks, move to utility file

2023-04-18 10:29 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +extern void
move it to utility file

2023-04-18 10:29 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/hooks.h
> +#include "tcop/cmdtag.h"
why this header? If for pointer types use forwards declaration

2023-05-03 06:27 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/hooks.h
> +
unnecessary change

2023-05-03 06:27 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +extern void
why extern here?

2023-05-03 08:59 UTC, kritika-0601 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +extern void
Yeah, I will remove it.

2023-05-08 05:11 UTC, surendravishnoi submitted a review, later dismissed

2023-05-08 06:43 UTC, surendravishnoi approved these changes, later dismissed

2023-06-12 06:22 UTC, HarshLunagariya requested changes

2023-06-12 06:22 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +    CreateFunctionStmt *stmt = (CreateFunctionStmt *)parsetree;
Please fix the indentation.

2023-06-12 06:22 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +			}
Please fix indentation.

2023-06-12 06:22 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +
Remove this line.

2023-06-12 17:09 UTC, HarshLunagariya approved these changes

2023-06-13 07:41 UTC, shardgupta approved these changes

2023-06-13 07:41 UTC, merged