systypes and sysusers should exist in DBO schema
babelfish-for-postgresql/babelfish_extensions pull request #1465
Opened 2023-04-25 18:57 UTC by Suthapalli-Ramya-satya-vasavi-srija

Previously the views(syscolumns, sysforeignkeys, sysindexes, sysobjects, syscharsets, sysconfigures, syscurconfigs, syslanguages, sysprocesses) are present in both 'sys' and 'dbo' schema but views(systypes and sysusers) are present only in 'sys' schema. They should be present in both 'sys' and 'dbo' schema.

This commit fixes the issue by making views systypes and sysusers accessible from both 'sys' and 'dbo' schema.

Task: BABEL-3731

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-25 19:06 UTC, xhfanhe submitted a review, later dismissed

2023-04-26 03:55 UTC, shalinilohia50 approved these changes, later dismissed

2023-04-28 06:15 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +select t.view_name from
You can add a comment here to describe the purpose of this view.

2023-04-28 06:17 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	 * 1. If view is an database specific check the behaviour in case of cross-db, if not working
NOTE is not very clear. We can remove it also.

2023-04-28 06:18 UTC, shalinilohia50 commented on test/JDBC/expected/Test_list_of_sys_catalog_present_in_dbo-dep-vu-verify.out
> +-- If observed the SQLServer behaviour these sys.sys% catalog views are present in
Don't mention the term SQL Server, rather use "T-SQL".

2023-04-28 08:23 UTC, HarshLunagariya requested changes

2023-04-28 08:23 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +GRANT SELECT ON sys.list_of_view_should_be_present_in_dbo_schema TO PUBLIC;
How about moving it to test file only?

2023-04-28 13:16 UTC, shalinilohia50 approved these changes

2023-04-28 13:49 UTC, HarshLunagariya approved these changes

2023-05-02 04:48 UTC, shardgupta approved these changes

2023-05-02 04:48 UTC, merged