Disallow ALTER ROLE of bbf roles/users in PG
babelfish-for-postgresql/babelfish_extensions pull request #1497
Opened 2023-05-04 08:47 UTC by Suthapalli-Ramya-satya-vasavi-srija

Previously, ALTER ROLE operations like password change, connection limit and valid until are allowed for bbf created roles/users. The bbf created roles/users are nologin by default so allowing listed above alter role operations doesn't seem correct.

This commit fixes the issue by disallowing all kind of alter role operations for bbf created roles/users.

TASK: BABEL-2976

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -** Add tests for different kind of alter role operations for bbf roles/users which should throw error, added tests for connection limit.

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-04 16:38 UTC, xhfanhe submitted a review, later dismissed

2023-05-05 05:24 UTC, HarshLunagariya requested changes

2023-05-05 05:24 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +	Form_pg_authid authForm;
Fix indentation.

2023-05-05 05:24 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +		}
Fix indentation.

2023-05-05 05:24 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +			ReleaseSysCache(tp);
Fix indentation.

2023-05-05 06:07 UTC, Suthapalli-Ramya-satya-vasavi-srija commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +	Form_pg_authid authForm;
Fixed in next revision

2023-05-05 06:07 UTC, Suthapalli-Ramya-satya-vasavi-srija commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +		}
Fixed in next Revision

2023-05-05 06:07 UTC, Suthapalli-Ramya-satya-vasavi-srija commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +			ReleaseSysCache(tp);
Fixed in next Revision

2023-05-05 08:03 UTC, shalinilohia50 approved these changes

2023-05-05 08:09 UTC, shardgupta approved these changes

2023-05-05 08:09 UTC, merged