Fix the order of params in a reordered parameter list of procedures
babelfish-for-postgresql/babelfish_extensions pull request #1624
Opened 2023-07-18 10:32 UTC by basasairohan

### Description

Currently, we are not handling the OUTPUT parameters in reordered parameter list of procedure arguments. This change adds support for handling the same. 

Signed-off-by: Sai Rohan Basa [bsrohan@amazon.com](mailto:bsrohan@amazon.com)

### Issues Resolved

BABEL-4235

### Test Scenarios Covered ###
* **Use case based -** 

* **Boundary conditions -**

* **Arbitrary inputs -** 

* **Negative test cases -** 

* **Minor version upgrade tests -** 

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-24 04:54 UTC, KushaalShroff requested changes

2023-07-24 04:54 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +					foreach(paramcell, stmt->params)
Can we add a comment here?

2023-07-24 04:54 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +							isFound = true;
Do we really need another variable for this?
Why can't you initialise j to -1 and then if you match this condition then set j.
Use j conditionally later

2023-07-24 04:54 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +					if (!isFound) j = i;
As a thumb rule in Postgres and babelfish we follow multi line if/else statements

2023-07-24 04:54 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			int			j;
Rename j to a more logical variable name - eg relativeArgIndex

2023-07-24 04:54 UTC, KushaalShroff commented on test/JDBC/expected/TestStoredProcedures.out
> +CREATE PROCEDURE sp_test20 (@a INT, @b INT OUTPUT) AS BEGIN Select @a as a, @b as b; SET @b=100; SET @a=1000; END;
Please add RPC tests as well, Just take the same sql batch and write the prep-exec cases.

2023-07-24 04:54 UTC, KushaalShroff commented on test/JDBC/expected/TestStoredProcedures.out
> +CREATE PROCEDURE sp_test20 (@a INT, @b INT OUTPUT) AS BEGIN Select @a as a, @b as b; SET @b=100; SET @a=1000; END;
Since this code change is touching all the param modes, can we add tests for those as well?

2023-07-24 10:47 UTC, basasairohan commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +					foreach(paramcell, stmt->params)
Added.

2023-07-26 05:30 UTC, KushaalShroff approved these changes

2023-07-26 05:52 UTC, merged