Rewrite OBJECTPROPERTY T-SQL function in C
babelfish-for-postgresql/babelfish_extensions pull request #1661
Opened 2023-07-31 16:18 UTC by basasairohan

### Description

Currently OBJECTPROPERTY function is implemented in SQL which is found to cause performance issues in the queries. This change will implement the function in C.

### Issues Resolved

BABEL-4317

Signed-off-by: Sai Rohan Basa [bsrohan@amazon.com](mailto:bsrohan@amazon.com)

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** Yes

* **Arbitrary inputs -** Yes

* **Negative test cases -** Yes

* **Minor version upgrade tests -** Yes

* **Major version upgrade tests -** Yes

* **Performance tests -** Tested locally for a query which was taking around 11 mins using old objectproperty function. For 1000 stored procedures. With the updated implementation of the objectproperty function, it is taking around 700 ms.

* **Tooling impact -** N/A

* **Client tests -** N/A

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-08-02 10:59 UTC, KushaalShroff requested changes

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	char *shipped_objects_not_in_sys_db[10][3] = {
If you declare this as a pointer then you would need to free it as well

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	char *namespace_name;
We need to free namespace_name!

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	char *shipped_objects_not_in_sys_schema[1][3] = {
Free shipped_objects_not_in_sys_schema (check the above comment)

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			tempnspname = pstrdup(TextDatumGetCString(datum));
Why are we not freeing any of the allocated memory after it's usage

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		// check whether the object name and object type is matching.
Nit: Comment style

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		if (pg_strcasecmp(type, shipped_objects_not_in_sys_schema[i][2]) == 0)
Why are we continuing if type is matching?
In this case we will continue for every view, why?

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			tempnspname = pstrdup(TextDatumGetCString(datum));
Also why do we need to use pstrdup here?

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		property = lowerstr(text_to_cstring(PG_GETARG_TEXT_P(1)));
Please use downcase_identifier

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		remove_trailing_spaces(property);
Use truncate_tsql_identifier

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +				type = "U";
Create a macro for all types and assign some int values to them. This way we can save on strcmp overhead.

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +					char	*temp = format_type_extended(procform->prorettype, -1, FORMAT_TYPE_ALLOW_INVALID);
free temp after using it

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			if (pg_proc_aclcheck(object_id, user_id, ACL_EXECUTE) == ACLCHECK_OK)
What is the behaviour for sql server when user does not have permission for that object?
Lets remember to add test case for that

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +					 * SQL inline table-valued function (IF), SQL scalar function (FN).
please add separate comments for TVFs

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			if (pg_attribute_aclcheck_ext(atdform->adrelid, atdform->adnum, user_id, ACL_SELECT, &isMissing) &&
Use pg_attribute_aclmask

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	if (!found)
Do we need found variable? we can utilise object_id or schema_id and check not null here

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		PG_RETURN_NULL();
Lets verify this behaviour

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		pg_strcasecmp(schema_origname, "public") == 0))
We should compare these with nspname and also add information_schema_tsql

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			int32		result;
use int or oid

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			PG_RETURN_INT32(1);
Ignoring this, expecting you to add comments for each hardcoded returns

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	/* OwnerId */
Expecting you to also add more comments for each property

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		table_close(indRel, RowExclusiveLock);
You are closing the table/cleanup after return

2023-08-02 10:59 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +bool is_ms_shipped(char *object_name, char *type, Oid schema_id)
Add comment on top of this function and its usecase

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +					char	*temp = format_type_extended(procform->prorettype, -1, FORMAT_TYPE_ALLOW_INVALID);
done

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +					 * SQL inline table-valued function (IF), SQL scalar function (FN).
added

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			if (pg_proc_aclcheck(object_id, user_id, ACL_EXECUTE) == ACLCHECK_OK)
SQL server will return NULL. I have added test cases for the same.

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	/* OwnerId */
added

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			PG_RETURN_INT32(1);
added

2023-08-04 13:21 UTC, basasairohan commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		table_close(indRel, RowExclusiveLock);
updated it

2023-08-07 10:19 UTC, KushaalShroff requested changes

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +#define EXTENDED_STORED_PROCEDURE 27
Why dont we use enum?

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> + * Funtion used to check whether the object is MS shipped. This is being used in objectproperty_internal.
Wrap long lines into multi-lines

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +#define AGGREGATE_FUNCTION 1
Add appropriate prefix for object_property type. This seems very generic.

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +	if (!OidIsValid(schema_id))
Why cant we rewrite if(!OidIsValid(schema_id)) as if(schema_id) ?

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +		pfree(property);
free just before return

2023-08-07 10:19 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/runtime/functions.c
> +			type != RULE)
This could be written more cleanly like
if (!( type == TSQL_STORED_PROCEDURE || type == REPLICATION_FILTER_PROCEDURE ))

2023-08-07 10:19 UTC, KushaalShroff commented on test/JDBC/expected/objectproperty.out
> +-- used to test when user does not have permission on the object
We need upgrade tests as well

2023-08-07 10:24 UTC, KushaalShroff commented on test/JDBC/expected/objectproperty.out
> +~~END~~
Seems like you have not validated the behaviour:
```
1> select objectproperty(object_id('information_schema.columns'), 'IsView')
2> go
           
-----------
          1

(1 rows affected)

2023-08-07 10:26 UTC, KushaalShroff commented on test/JDBC/expected/objectproperty.out
> +~~END~~
Based on this, we will need to rewrite information_schema name to information_schema_tsql

2023-08-08 17:32 UTC, KushaalShroff approved these changes

2023-08-08 17:32 UTC, KushaalShroff commented
Awaiting Performance improvement numbers before merge

2023-08-10 10:36 UTC, merged