Implemented fix for single byte and multi byte aliases
babelfish-for-postgresql/babelfish_extensions pull request #1812
Opened 2023-09-04 06:41 UTC by riyajain39

### Description

This pull request fixed the implementation for aliases contain both singlebyte and multibyte characters whose length is more than 64 bytes.

**Issue 1 :** Handle column and table aliases. 
Column alias does not work when alias length is more than or equals to 64 bytes in case of multibyte aliases. When query `select 1  as '您对“数据一览“中的车型，颜色，内饰，选装, ';` executes through T-SQL endpoint, it causes client to hang and throws protocol error in TDS stream. The logic of [pre_transform_target_entry](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_3_X_DEV/contrib/babelfishpg_tsql/src/hooks.c#L1395) was not handling the aliases contain multibyte characters whose length is more than 64 bytes accurately and overwriting the alias name in case of truncation. To address this problem, I redefined the function and implemented the conditions which will handle aliases delimited with square bracket and double quotes separately with other aliases. In other aliases, I added the conditions which will handle both truncated and untruncated aliases separately. 

**Issue 2 :** Aliases with multibyte chars cause MVU failure.
When establishing a view of alias with multibyte chars through T-SQL endpoint and retrieving it's definition from PG end point, extra unreadable chars are appearing at the end of the alias and even we can not use this view through tsql endpoint as it throws protocol error in TDS stream. But while we use similar alias on PG end point, we are able to retrieve it's correct definition. This discrepancy in behaviour is causing MVU failure. After implementing a fix, the correct alias definition is obtained from the PG endpoint, which rectifies the issue.

 
### Issues Resolved

BABEL-4231

### Test Scenarios Covered ###

* **Use case based -** Added test case from original bug.

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -** Added testcase for 14.latest to 15.latest. 

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-22 12:01 UTC, Deepesh125 requested changes

2023-09-22 12:01 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +                * After truncation, maximum truncated length of alias can be 60
add details bit more here, it could be 61 to 63 in case of multibyte chars and we need to handle those cases only.

2023-09-22 12:01 UTC, Deepesh125 commented on .github/configuration/upgrade-test-configuration.yml
> +    version: '14.10',
Make sure we get approval for this change from @rohit01010 or @basasairohan

2023-09-22 12:01 UTC, Deepesh125 commented on test/JDBC/expected/14_10__preparation__BABEL-2877-vu-prepare.out
> +-- Defaults at different positions
Make sure we get approval from original writer of BABEL-2877 tests, same for other test files

2023-09-22 12:01 UTC, Deepesh125 commented on test/JDBC/upgrade/14_10/schedule
> +BABEL-4231
what about upgrade tests for BABEL-4384

2023-09-25 05:36 UTC, riyajain39 commented on .github/configuration/upgrade-test-configuration.yml
> +    version: '14.10',
Yes, I have confirmed from them.

2023-09-25 05:37 UTC, riyajain39 commented on test/JDBC/expected/14_10__preparation__BABEL-2877-vu-prepare.out
> +-- Defaults at different positions
Yes, I discussed with Rishabh about it. He suggested me to do this.

2023-09-25 05:54 UTC, riyajain39 commented on test/JDBC/upgrade/14_10/schedule
> +BABEL-4231
Resolved.

2023-09-25 07:42 UTC, Deepesh125 approved these changes

2023-09-25 07:44 UTC, merged