Add collation when initialising scan keys for sys.varchar
babelfish-for-postgresql/babelfish_extensions pull request #1832
Opened 2023-09-11 06:27 UTC by tanscorpio7

### Description

### Issues Resolved

BABEL-4389

### Test Scenarios Covered ###

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-11 13:05 UTC, Deepesh125 requested changes

2023-09-11 13:05 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				bbf_view_def_idx_rel->rd_indcollation[0], F_INT2EQ,
datatype of this field is SMALLINT so we do nt need to specify the collation here.

2023-09-11 13:05 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				bbf_view_def_idx_rel->rd_indcollation[1], F_TEXTEQ,
data type of this field is sys.sysname whose collation would always be same as `tsql_get_server_collation_oid_internal(false)` so we could avoid opening table index to gather the collation.

2023-09-11 13:05 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				bbf_view_def_idx_rel->rd_indcollation[1], F_TEXTEQ,
Applicable to all other places

2023-09-12 06:54 UTC, Deepesh125 approved these changes

2023-09-12 07:01 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/catalog.c
> -	ScanKeyInit(&scanKey[1],
have we validated that no other babel catalogs have this issue?

2023-09-12 07:02 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> -	ScanKeyInit(&scanKey[1],
@tanscorpio7 Is preparing document where we need similar kind of fix.

2023-09-12 09:41 UTC, merged