Create DB Performance improvements
babelfish-for-postgresql/babelfish_extensions pull request #1899
Opened 2023-10-09 14:00 UTC by tanscorpio7

### Description

In Multi DB mode, as the number of databases increases, so does the time to create the next new DB.
This is because we create three internal roles for each new DB and internally when run the DB subcommands, multiple calls to roles_is_member_of("sysadmin") is made. Now that output of this list contains all the three roles of every db created. This is the major reason for the perfomance degradation of CREATE DB command.

We fix this in three different places.

1. getAvailDbid - this functions makes a call to nextval function, which by default checks for current user's permission and makes a call to roles_is_member_of. Instead we could call the **nextval_internal** which is the same function but with the additional option of check permissions flag which we will set to false. To double check we can just ensure that the current user is "sysadmin" when getAvailDbid is called. (Currently we only call this when user is sysadmin)

2. Set temporary user when creating schema - when we create the dbo and guest schema for the new database, the create schema function fetches all the roles that current role is member of (recursively) to check if if current role can actually become the target schema owner role. To bypass this we can **assume the newdb_dbo role** when creating these schemas. In this case all the roles that newdb_dbo is member of will be fetched, but this list is much smaller than sysadmin.

3. Select best grantor - Select best grantor first fetches the roles_list that sysadmin is member of and then start checking for permissions. But sysadmin is always the first to be checked. That is sysadmin is always top of the roles_list. 
We can add a quick check to this. That is, first check if current role is sysadmin and can it give us all the permission needed. If yes, simply return. Note** This does not change any behaviour since this will anyway be done in the first loop after fetching roles_list. We are instead running the first loop before fetching the whole list.

4. Set newdb_dbo user when creating sysdatabases view in new db

This removes almost all the increase seen in create db execution time.
DBs10 created in 2 ms
DBs500 created in 3 ms
DBs1000 created in 4 ms
DBs3000 created in 9 ms
(local stats)

#### Engine PR: https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/pull/234
#### Extension PR: https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/1899

### Issues Resolved

[BABEL-3869](https://jira.rds.a2z.com/browse/BABEL-3869)

Signed-off-by: Tanzeel Khan <tzlkhan@amazon.com>

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-09 15:05 UTC, shalinilohia50 commented
Could you please mention how much improvement we have observed after these changes?

2023-10-10 09:02 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		dbid = nextval_internal(seqid, false);
just to be safe, add assert before calling nextval_internal - `Assert(OidIsValid(seqid))`

2023-10-11 07:00 UTC, HarshLunagariya requested changes

2023-10-11 07:00 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		expected_stmt_num = 6;
Shouldn't it be 4?

2023-10-11 07:00 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -			/* make sure later steps can see the object created here */
Unwanted change

2023-10-11 07:06 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -
We shouldn't do it. It may break existing applications and tooling support.
Refer - https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-compatibility-views/sys-sysdatabases-transact-sql.md

2023-10-11 07:06 UTC, shalinilohia50 requested changes

2023-10-11 07:06 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		expected_stmt_num = 6;
Yes, it should be 4.

2023-10-11 07:06 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
Since we are removing this create view statement from here, we should create this view `sysdatabases` in `ownership.sql`.

2023-10-11 08:52 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -
Select * from sys.sysdatabases
Select * from sysdatabases
stiil work, post this change

2023-10-11 09:13 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
seems we already create it in ownership

2023-10-11 10:26 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
Right.
We need to resolve `dbo.sysdatabases` to `sys.sysdatabases` as discussed.

2023-10-11 14:25 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -
Not removing the create view stmts for dbo.sysdatabases
Instead just setting the current_user to dbo for create and alter view stmts, similar to create schema stmts
cc: @shalinilohia50

2023-10-11 14:27 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
This approach requires more planning, dropping it for now

2023-10-11 14:53 UTC, shalinilohia50 approved these changes

2023-10-12 09:46 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
I see the performance numbers in the description:
```
This removes almost all the increase seen in create db execution time.
DBs10 created in 2 ms
DBs500 created in 3 ms
DBs1000 created in 4 ms
DBs3000 created in 9 ms
(local stats)
```
Are these the latest numbers after all 4 fixes done in this PR(including the engine change)?

2023-10-12 11:15 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -	appendStringInfo(&query, "CREATE VIEW dummy.sysdatabases AS SELECT * FROM sys.sysdatabases; ");
These numbers can ONLY be seen with all 4 changes, I missed fix number 4 in earlier revisions.
Also numbers are for local dev dsk

2023-10-12 18:23 UTC, forestkeeper approved these changes

2023-10-12 18:25 UTC, merged