Rewrite getdate functions in C
babelfish-for-postgresql/babelfish_extensions pull request #1908
Opened 2023-10-10 19:51 UTC by hash-16

### Description

Rewrite the sysutcdatetime and getutcdate as C functions to directly use postgres internal timezone function.

Performance (getdate test file) :-
Earlier :- 18 seconds
Now :- 5 seconds

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-11 06:24 UTC, KushaalShroff commented
Please update description as per guidelines: add issue and why/how it affected performance and how you fixed it.
We need numbers for performance before your change for AT TIME ZONE.

2023-10-11 06:25 UTC, KushaalShroff commented
No reverts to the SLA extension? :)

2023-10-12 18:19 UTC, forestkeeper approved these changes

2023-10-13 05:43 UTC, KushaalShroff requested changes
Requesting changes so as to not allow merge like done before! Will review by EOD

2023-10-16 15:36 UTC, KushaalShroff approved these changes

2023-10-16 15:48 UTC, merged