Performance improvements for SSMS query while trying to expand stored procedures
babelfish-for-postgresql/babelfish_extensions pull request #1923
Opened 2023-10-16 05:44 UTC by basasairohan

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-20 10:20 UTC, KushaalShroff requested changes

2023-10-20 10:20 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +and has_table_privilege(quote_ident(s.nspname) ||'.'||quote_ident(t.relname), 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,TRIGGER')
Can we call has_table_privilege with t.oid. The string creation seems redundant

2023-10-20 10:20 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +-- details of user defined and system views
Lets add comment on these additional unions on why they are needed

2023-10-20 10:20 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +          when p.proretset then
Is this valid for TSQL?

2023-10-23 08:19 UTC, basasairohan commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +          when p.proretset then
Yes.

2023-10-23 08:19 UTC, basasairohan commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +and has_table_privilege(quote_ident(s.nspname) ||'.'||quote_ident(t.relname), 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,TRIGGER')
done

2023-10-23 08:19 UTC, basasairohan commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +-- details of user defined and system views
done

2023-10-25 09:11 UTC, KushaalShroff approved these changes

2023-10-25 10:12 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/sys_views.sql
> +left join sys.babelfish_namespace_ext ext on (s.nspname = ext.nspname and ext.dbid = sys.db_id())
can we directly join pg_class with babelfish_namespace_ext on line 1303?

2023-10-25 10:16 UTC, Deepesh125 approved these changes

2023-10-25 10:18 UTC, merged