Use appropriate datatype for sys.format, sys.format_datetime, sys.format
babelfish-for-postgresql/babelfish_extensions pull request #1987
Opened 2023-11-06 16:27 UTC by basasairohan

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-08 06:00 UTC, sumitj824 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.3.0--3.4.0.sql
> +ALTER FUNCTION sys.format_datetime(anyelement, NVARCHAR, VARCHAR, VARCHAR) RENAME TO format_datetime_deprecated_3_3;
The name of deprecated objects should be `3_4_0` everywhere.

2023-11-08 06:03 UTC, sumitj824 requested changes

2023-11-08 06:03 UTC, sumitj824 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.3.0--3.4.0.sql
> +CALL sys.babelfish_drop_deprecated_object('function', 'sys', 'format_datetime_deprecated_3_3');
We should drop after renaming only, it will easier to check if object is dropped or not.

2023-11-08 08:53 UTC, sumitj824 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.3.0--3.4.0.sql
> +DROP PROCEDURE sys.babelfish_drop_deprecated_object(varchar, varchar, varchar);
Along with this, Could you also move the `reset search_path` and `run analyze` part to the bottom of upgrade script?

2023-11-09 04:41 UTC, sumitj824 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.3.0--3.4.0.sql
> +
I don't see any problem with this ordering, but ideally drop should first then analyze and then reset search path.

2023-11-09 05:22 UTC, sumitj824 approved these changes

2023-11-09 05:29 UTC, Deepesh125 requested changes

2023-11-09 05:29 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/datatype_string_operators.sql
>  AS 'babelfishpg_tsql', 'format_numeric' LANGUAGE C IMMUTABLE PARALLEL UNSAFE;
This is C language function, you also need to deprecate C function. Check https://quip-amazon.com/UGJjA2lJSW6B/Changing-the-datatypes-of-columns-for-some-views#temp:C:PFP20d0854563b1b603a9ca8e64e

2023-11-09 05:29 UTC, Deepesh125 commented on test/python/expected/upgrade_validation/expected_dependency.out
> +Function sys.format_numeric(anyelement,sys.nvarchar,sys."varchar",sys."varchar",integer)
Lets add dependency test cases

2023-11-10 06:50 UTC, Deepesh125 approved these changes

2023-11-10 06:50 UTC, merged