Stored the permissions in a single column using bits
babelfish-for-postgresql/babelfish_extensions pull request #2044
Opened 2023-11-21 09:30 UTC by shalinilohia50

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-21 16:28 UTC, kuntalghosh requested changes

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +  permission SMALLINT,
Should be NOT NULL, right?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +	CommandCounterIncrement();
Why is this needed?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +			return true;
Not ending the scan and not closing the table. Have you added a test for this? Otherwise, the test should have complained.

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +				grant_perms_to_each_obj(db_name, object_type, schema_name, object_name, grantee, "references");
Try to execute a single GRANT statement with all the permissions at once. Otherwise, it'll execute individual GRANT statement

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +	parsetree_list = gen_grantschema_subcmds(schema_name, rolname, stmt->is_grant, stmt->with_grant_option, priv_name);
Shouldn't you free this list?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +		}
Including the same condition multiple times in the same if..else block is not a good coding practice. Please write it as following:
```
if (grant)
{
 if (check_bbf_schema_for_entry())
    // update the entry
 else
   // add the entry
}
else
{
 if (check_bbf_schema_for_entry())
    // update the entry
}
```

For revoke, why is this a no-op if an entry is not found?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						}
whitespace

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +									if(old_priv!= 32 || ((old_priv)|(32)) != old_priv)
Use a macro for 32 (should have a meaningful name)

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			exec_gen_grantschema(schema_name, rolname, stmt, "execute");
Send privilege names as a list and execute a single statement

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
>  						const char *logical_schema = NULL;
Why are you handling CREATE LOGICAL DATABASE in OBJECT_TABLE? What other subcommand can fall under this category?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +									queryEnv, dest, qc);
Shouldn't this call exec_stmt_grantschema internally and update the catalog? If not, when exec_stmt_grantschema is called exactly?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +										flag = true;
What does this flag indicate?

2023-11-21 16:28 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pltsql.h
> +
Please use the same ACL [defined](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/BABEL_3_X_DEV__PG_15_X/src/include/nodes/parsenodes.h#L82) in PG.  This will help us reusing some internal functions/macros if required. For example you can use privilege_to_string() to retrieve the values or ACLITEM_SET_PRIVS to set the privileges.

2023-11-21 18:24 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +	parsetree_list = gen_grantschema_subcmds(schema_name, rolname, stmt->is_grant, stmt->with_grant_option, priv_name);
I don't think it's needed. [References](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/a695d88e21a3b0418f2d49a1539a759e48be7d19/contrib/babelfishpg_tsql/src/dbcmds.c#L525)

2023-11-21 18:32 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			exec_gen_grantschema(schema_name, rolname, stmt, "execute");
We have separate sub commands for below privileges:
 1. [select, insert, update, references] -> Applicable for Tables
 2. [execute] -> Applicable for Functions and Procedures
 So, we cannot execute a single statement if a grant statement specifies multiple privileges like `insert, select, update`

2023-11-21 18:32 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				grant_perms_to_each_obj(db_name, object_type, schema_name, object_name, grantee, "references");
We have separate sub commands for below privileges:

1. [select, insert, update, references] -> Applicable for Tables
2. [execute] -> Applicable for Functions and Procedures
So, we cannot execute a single statement if a grant statement specifies multiple privileges like insert, select, update

2023-11-21 18:35 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +									queryEnv, dest, qc);
We have defined a separate node `PLtsql_stmt_grantschema` for `GRANT/REVOKE on SCHEMA` statement which executes `exec_stmt_grantschema`

2023-11-21 18:36 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +										flag = true;
This specifies if there is permission granted to a specific column in a table. 
Renaming it to something readable.

2023-11-21 19:21 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +		}
For REVOKE:
1. Update the entry if it exists already. 
2. Otherwise, do nothing.

2023-11-21 20:05 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/catalog.c
> +	CommandCounterIncrement();
Not needed here.

2023-11-21 20:06 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/catalog.c
> +			return true;
Addressed it.

2023-11-21 20:15 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pl_handler.c
>  						const char *logical_schema = NULL;
One of the CREATE DATABASE subcommands was `GRANT SELECT ON dummy.sysdatabases TO dummy;` which we avoided here. 
With this [commit](https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/08c886f889461c0e9e71f081167d06ba9d56be1d), looks like it's not needed anymore.

2023-11-21 20:32 UTC, KushaalShroff requested changes
I came across a flaw with the GRANT/REVOKE on schema code/design. In the following example you see Babelfish allows us to create objects with same names and also overload procedures and functions:
```
1> create table t (a int)
2> go

1> create procedure t as select 1
2> go

1>  create procedure t(@a int) as select @a
2> go
```
1. You are not scanning/looking up  based on object_type at multiple places in the code.
a. You are going to return the first matching entry in table irrespective of the object_type.
b. You are inserting NULL for object_type at [one place](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/a695d88e21a3b0418f2d49a1539a759e48be7d19/contrib/babelfishpg_tsql/src/pl_exec-2.c#L3776), why?
2. How are you gonna support Grants/Revokes on overloaded procedures and functions?
a. In the above example One grant/revoke statement will affect unintended objects, that seems like a critical bug to me
3. We need to add these test cases

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +  permission SMALLINT,
+1

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +			return true;
+1, but that would only come into consideration if you check the logs. There would have been explicit cache leak references

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +	PlannedStmt		*wrapper;
We need to free 3 of these, right?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +			if((permission & PRIVILEGE_BIT_FOR_EXECUTE) == PRIVILEGE_BIT_FOR_EXECUTE)
Why do we need to equate???
Simple `if(permission & PRIVILEGE_BIT_FOR_EXECUTE)` should work!

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	return privilege_maskInt;
WHY?
Why cant we simply store privilege_maskInt during parsing? You are parsing a string and storing a list of strings in antlr and then coming here to convert List of strings to int. Seems unnecessarily costly to me.

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +				grant_perms_to_each_obj(db_name, object_type, schema_name, object_name, grantee, "references");
What if grant_perms_to_each_obj -> ProcessUtility throws error? It will leave the table bbf_schema_rel  open, right?
Practice safer coding techniques by using try/catch blocks

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			exec_gen_grantschema(schema_name, rolname, stmt, "execute");
I agree, we can write a single batch for all grant queries and get it executed as a batch, if thats possible. Is it? The code will be cleaner in that case

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +		if((privilege_maskInt & PRIVILEGE_BIT_FOR_EXECUTE) == PRIVILEGE_BIT_FOR_EXECUTE)
Simple if(permission & PRIVILEGE_BIT_FOR_EXECUTE) should work, right?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			if(old_priv!= privilege_maskInt || ((old_priv|privilege_maskInt) != old_priv))
Why do we need the first condition at all?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			int16 old_priv = get_bbf_schema_privilege(stmt->schema_name, PERMISSIONS_FOR_ALL_OBJECTS_IN_SCHEMA, rolname);
Isnt old_priv already defined outside the block? :)

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			old_priv = get_bbf_schema_privilege(stmt->schema_name, PERMISSIONS_FOR_ALL_OBJECTS_IN_SCHEMA, rolname);
Same statement in both conditions can be/should be executed outside

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			if(old_priv!= privilege_maskInt || ((old_priv)&(~privilege_maskInt)) != old_priv)
This condition has totally confused me😅
Can you explain? Also requires comments!

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			if(old_priv!= privilege_maskInt || ((old_priv)&(~privilege_maskInt)) != old_priv)
Why cant we simply check `old_priv & privilege_maskInt` Is not 0?
If it is non-zero then obviously we have to revoke the intersection of permissions!

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +		 * In case of REVOKE, we remove the new privilege and keep the previous privilege as it is.
Why are we calling it new privilege then?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +	tuple_bbf_schema = heap_getnext(scan, ForwardScanDirection);
sys, right?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +						const char *object_type,
I cannot the use of object_type, why is it needed?
Was there no compiler warning at the time of build?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +  PRIMARY KEY(dbid, schema_name, object_name, grantee)
OBJECT_TYPE should be part of primary key too, right?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +	ScanKeyEntryInitialize(&scanKey[2], 0,
We need to scan based on object type too!!!

How are you going to distinguish between a table and procedure?
```
1> create table t (a int)
2> go

1> create procedure t as select 1
2> go
```

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/catalog.c
> +				CStringGetDatum(grantee));
Based on this logic you are going to return the first object which matches irrespective of the object_type.
What if the first one was a table but user was granting for a procedure?

2023-11-21 20:32 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			add_entry_to_bbf_schema(stmt->schema_name, PERMISSIONS_FOR_ALL_OBJECTS_IN_SCHEMA,  privilege_maskInt, rolname, NULL);
Why are you inserting NULL for object_type?

2023-11-22 05:14 UTC, closed without merging

2023-11-22 05:18 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	return privilege_maskInt;
I tried storing bitmask during parsing but then to do this change was eventually leading channge in  structures' definition in postgres, heance we need to store strings only during parsing.

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +	tuple_bbf_schema = heap_getnext(scan, ForwardScanDirection);
Yeah, in some place, it's a heap_getnext and in some place it's a sys scan.

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +	CommandCounterIncrement();
Whats the next step?

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +				grant_perms_to_each_obj(db_name, object_type, schema_name, object_name, grantee, "references");
But, in a single iteration of the loop, the object type won't change, right?

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/catalog.c
> +				grant_perms_to_each_obj(db_name, object_type, schema_name, object_name, grantee, "references");
In case of an error, the table will be closed automatically unless we catch the error explicitly.

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_exec-2.c
> +			exec_gen_grantschema(schema_name, rolname, stmt, "execute");
@shalinilohia50 But, for a single exec_stmt_grantschema execution, the object type won't change, right?

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +									queryEnv, dest, qc);
Okay. But, exec_stmt_grantschema also updates the catalog. So, do you need to update it here as well?

2023-11-22 06:16 UTC, kuntalghosh commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	return privilege_maskInt;
As I mentioned, use ACL [defined](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/BABEL_3_X_DEV__PG_15_X/src/include/nodes/parsenodes.h#L82) in PG. It provides a lot of APIs for these.