Fix bugs for CREATE FULLTEXT INDEX logic for supporting primary key indexes
babelfish-for-postgresql/babelfish_extensions pull request #2067
Opened 2023-11-24 12:36 UTC by roshan0708

### Description

This commit resolved the bug that was found when we execute the following query to create a unique index during table creation and when we use that index name for fulltext index creation, it was failing.

Before:
```
CREATE TABLE tableName(ID INT NOT NULL CONSTRAINT index
```

### Issues Resolved

JIRA: BABEL-4383
Signed-off-by: Roshan Kanwar [rskanwar@amazon.com](mailto:rskanwar@amazon.com)

### Test Scenarios Covered ###
* **Use case based -** Added

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-24 13:11 UTC, roshan0708 commented
Failure in version upgrade for 15.5 to target-latest is due to diff in prepare test, we are getting the previous behaviour because the current code changes are not in 15.5. We can ignore this failure and it will get fixed once this change gets cherry-pick in stable branch.

2023-11-28 06:48 UTC, kuntalghosh submitted a review, later dismissed

2023-11-28 06:53 UTC, HarshLunagariya approved these changes

2023-11-28 06:55 UTC, HarshLunagariya requested changes
Changes looks good. Please resolve workflow failures.

2023-11-28 06:56 UTC, HarshLunagariya approved these changes

2023-11-28 12:32 UTC, roshan0708 commented
Identical changes are merged to stable.

2023-11-28 12:33 UTC, jsudrik approved these changes
Already merged in stable. Approved.

2023-11-28 12:33 UTC, merged