Improve performance of sp_tablecollations_100 (spt_tablecollations_view)
babelfish-for-postgresql/babelfish_extensions pull request #2253
Opened 2024-01-15 10:31 UTC by tanscorpio7

### Description

### Issues Resolved

[BABEL-3466]

### Sign-Off

Signed-off-by: Tanzeel Khan <tzlkhan@amazon.com>

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-16 05:27 UTC, ahmed-shameem requested changes

2024-01-16 05:27 UTC, ahmed-shameem commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +        CAST(c.name AS sys.varchar)      AS name,
I would suggest you to replace all the views with pg_catalog. For example, c.object_id is same as pg_class.oid. You can check how are we obtaining the value of a particular column from the underlying view definition. IMO, if we can get rid of using all view and use only pg catalogs, that would increase the performance better.

NOTE: Make sure that we are obtaining the set of results back.

2024-01-16 06:30 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +        CAST(c.name AS sys.varchar)      AS name,
I did try that, performance was same as this change.

2024-01-22 13:31 UTC, Deepesh125 approved these changes

2024-01-22 14:42 UTC, rohit01010 approved these changes

2024-01-23 10:53 UTC, merged