Column is_fixed_role for 'sysadmin' should return 1
babelfish-for-postgresql/babelfish_extensions pull request #231
Opened 2022-05-24 06:19 UTC by shalinilohia50

Column is_fixed_role for 'sysadmin' should return 1

Task: BABEL-3225
Signed-off-by: Shalini Lohia <lshalini@amazon.com>

2022-07-11 03:56 UTC, surendravishnoi requested changes
Please make commit message more descriptive. Also, add upgrade tests if applicable.

2022-07-11 07:21 UTC, shalinilohia50 commented
> Please make commit message more descriptive. Also, add upgrade tests if applicable.

Updated the commit message. Not sure if upgrade tests are applicable for this minor change.

2022-07-13 08:52 UTC, surendravishnoi approved these changes

2022-07-13 16:34 UTC, macwoody approved these changes

2022-07-13 16:34 UTC, merged