Support dot identifiers syntax for CREATE/DROP FULLTEXT INDEX
babelfish-for-postgresql/babelfish_extensions pull request #2396
Opened 2024-02-27 11:25 UTC by roshan0708

This commit adds support for different syntax of identifiers - including spaces, dots, double quotes, square brackets, etc. for CREATE and DROP FULLTEXT INDEX statement.

Task: BABEL-4785

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-27 15:30 UTC, basasairohan requested changes

2024-02-27 15:30 UTC, basasairohan commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +	std::string table_info = ::getFullText(tctx);
This variable seems redundant. Please remove it.

2024-02-27 15:30 UTC, basasairohan commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +							downcase_truncate_identifier(schema_name.c_str(), schema_name.length(), true),
nit : indentation

2024-02-28 10:16 UTC, rishabhtanwar29 approved these changes
Let's have a generic title like: 
Support generic identifier names with FULLTEXT INDEX syntax

2024-02-28 10:16 UTC, rishabhtanwar29 commented on test/JDBC/input/full_text_search/BABEL-4785-vu-cleanup.sql
> +GO
Nit: add newline at end of each new file.

2024-02-28 10:21 UTC, rishabhtanwar29 commented on test/JDBC/expected/BABEL-4785-vu-prepare.out
> +CREATE TABLE fts_schema_test."fts object with dots and spaces in quotes"(id int not null, name text)
Let's have test with special characters as well like {}\/ # etc

2024-02-28 13:14 UTC, basasairohan approved these changes
LGTM

2024-02-29 18:01 UTC, shardgupta approved these changes

2024-02-29 18:03 UTC, merged