Fix metadata consistency check of schema name for babelfish_schema_permissions catalog
babelfish-for-postgresql/babelfish_extensions pull request #2595
Opened 2024-05-21 10:54 UTC by sumitj824

### Description
This commit fix the metadata consistency check of schema name for babelfish_schema_permissions catalog which has been introduced as part Grant on Schema support. Earlier it used to keep failing because we were comparing logical schema name with physical schema name in the check.

### Issues Resolved

Task: BABEL-4985

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** Yes

* **Arbitrary inputs -** NA

* **Negative test cases -**  NA

* **Minor version upgrade tests -** Yes

* **Major version upgrade tests -** Yes

* **Performance tests -** NA

* **Tooling impact -** NA

* **Client tests -** NA

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-21 21:13 UTC, xhfanhe submitted a review, later dismissed

2024-05-22 05:38 UTC, HarshLunagariya approved these changes

2024-05-22 06:29 UTC, Deepesh125 requested changes

2024-05-22 06:29 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> +	physical_schema_name = get_physical_schema_name(get_db_name(DatumGetInt16(dbid)), TextDatumGetCString(schema_name));
just check that dbid and schema_name is not null before this

2024-05-22 06:29 UTC, Deepesh125 commented on test/JDBC/expected/1_GRANT_SCHEMA-vu-prepare.out
> +CREATE SCHEMA babel_4768_schema_longer_than_64_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
also have a schema name with special characters, emojis, etc (quoted identifiers also)

2024-05-22 11:20 UTC, Deepesh125 approved these changes

2024-05-22 16:21 UTC, merged