Support like for AI collation for Sublink and CoerceViaIO nodes
babelfish-for-postgresql/babelfish_extensions pull request #2640
Opened 2024-06-03 10:23 UTC by ahmed-shameem

### Description

While supporting LIKE operator for AI collation, we have done defensive coding where we throw unrecognised node error for the nodes which we have not handled explicitly. We have found such issues where we throw the error for sublink and CoerceViaIO node type. This commit adds the support for like for AI collations for Sublink and CoerceViaIO node type. 

### Issues Resolved

BABEL-4998
Signed-off-by: Shameem Ahmed [shmeeh@amazon.com](mailto:shmeeh@amazon.com)

### Test Scenarios Covered ###
* **Use case based -** YES

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-03 14:42 UTC, Deepesh125 requested changes

2024-06-03 14:42 UTC, Deepesh125 commented on test/JDBC/expected/non_default_server_collation/japanese_ci_as/test_like_for_AI-vu-verify.out
> +SELECT 1 WHERE 'Götterdämmerung' LIKE (SELECT 'Götterdämmerung' COLLATE Latin1_General_CI_AI);
can we add some tests cases where sublink appears in target list of the query. For example, select col_a LIKE (SELECT 'Götterdämmerung' COLLATE Latin1_General_CI_AI) FROM some_table 

here, subquery may have different forms

2024-06-06 10:47 UTC, ahmed-shameem commented on test/JDBC/expected/non_default_server_collation/japanese_ci_as/test_like_for_AI-vu-verify.out
> +SELECT 1 WHERE 'Götterdämmerung' LIKE (SELECT 'Götterdämmerung' COLLATE Latin1_General_CI_AI);
This will throw syntax error. Added tests which contains sublink in target list (please refer to case CASE 22: Sublink (with other combinations))

2024-06-06 13:08 UTC, Deepesh125 approved these changes

2024-06-06 14:23 UTC, merged