Added wrapper functions for REPLICATE() Function to fix issue with input containing multi-byte characters.
babelfish-for-postgresql/babelfish_extensions pull request #2740
Opened 2024-07-14 13:54 UTC by rohit01010

### Description
Currently for string function `REPLICATE()` the existing definition takes input as type `TEXT` and return type is `VARCHAR`. This leads to incorrect output for input containing multi-byte characters with `NCHAR` and `NVARCHAR` datatype for input, as the return datatype should have been `NVARCHAR` for `NCHAR` and `NVARCHAR` datatype. This PR will fix this issue by adding wrapper functions with correct input and return datatype for `REPLICATE()` function.

Authored-by: Rohit Bhagat [rohitbgt@amazon.com](mailto:rohitbgt@amazon.com)
Signed-off-by: Rohit Bhagat [rohitbgt@amazon.com](mailto:rohitbgt@amazon.com)

### Issues Resolved

BABEL-862

### Test Scenarios Covered ###
* **Use case based -** YES

* **Boundary conditions -** YES

* **Arbitrary inputs -** YES

* **Negative test cases -** YES

* **Minor version upgrade tests -** YES

* **Major version upgrade tests -** YES

* **Performance tests -** NO

* **Tooling impact -** NO

* **Client tests -** NO

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-25 13:32 UTC, shah-nirmit requested changes

2024-07-25 13:32 UTC, shah-nirmit commented on test/JDBC/expected/replicate-vu-verify.out
> +??·???                   ??·???                   ??·???                   ??·???
Is this a known issue?

2024-07-25 13:32 UTC, shah-nirmit commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.6.0--3.7.0.sql
> +LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
STRICT? Also check fresh install files

2024-07-25 13:32 UTC, shah-nirmit commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.6.0--3.7.0.sql
> +LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
STRICT?

2024-07-25 17:21 UTC, rohit01010 commented on test/JDBC/expected/replicate-vu-verify.out
> +??·???                   ??·???                   ??·???                   ??·???
Yes

2024-07-25 17:51 UTC, rohit01010 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.6.0--3.7.0.sql
> +LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
Done

2024-07-25 17:51 UTC, rohit01010 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.6.0--3.7.0.sql
> +LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE;
Done

2024-07-26 03:40 UTC, shah-nirmit approved these changes
LGTM

2024-07-26 13:04 UTC, shah-nirmit approved these changes

2024-07-29 05:19 UTC, Deepesh125 approved these changes

2024-07-29 06:48 UTC, merged