Fix behaviour of error message for GRANT
babelfish-for-postgresql/babelfish_extensions pull request #2810
Opened 2024-07-30 11:32 UTC by aswiniip

### Description
Currently on executing queries like `GRANT EXECUTE ON PROCEDURE::test TO public;`, babelfish throws error with error message `GRANT ON PROCEDURE is not currently supported in Babelfish` which is incorrect as the above query has an incorrect syntax. With this change it now shows `syntax error` for such cases and `not currently supported` for allowed object types (according to GRANT documentation) which are not supported by us currently.

The issue arrised because the GRANT query is being successfully parsed by our antlr parser and then the check for supported/unsupported occurs resulting in the error being thrown in the `TsqlUnsupportedFeatureHandler()` rather than the antlr parser.

### Changes Made:
In the rule definition of GRANT/REVOKE/DENY in `TSqlParser.g4`, `object_type` is used which contains some types like PROCEDURE, TABLE which are not syntactically correct according to the GRANT/REVOKE/DENY documentation. In this PR, I have created a new `permission_object_type` which contains only those types which are syntactically correct for GRANT/REVOKE/DENY and added relevant tests for the same. After this change, babelfish throws error during the parsing and gives syntax error.

### Issues Resolved
BABEL-5079

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** Yes

* **Arbitrary inputs -** Yes

* **Negative test cases -** Yes

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [x] Commits are signed per the DCO using --signoff 

Signed-off-by: P Aswini Kumar [aswinii@amazon.com](mailto:aswinii@amazon.com)

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-30 14:35 UTC, HarshLunagariya approved these changes

2024-07-31 03:33 UTC, forestkeeper commented on contrib/babelfishpg_tsql/antlr/TSqlParser.g4
> +    : APPLICATION ROLE
We should write this into format like : 
(USING_SYMBOL | TYPE_SYMBOL| .. | )

2024-07-31 03:33 UTC, forestkeeper commented on contrib/babelfishpg_tsql/antlr/TSqlParser.g4
> +    : APPLICATION ROLE
That format the antlr performance would be better

2024-07-31 03:34 UTC, forestkeeper requested changes
Pls refer to this blog and rewrite some of the antlr rules : https://tomassetti.me/improving-the-performance-of-an-antlr-parser/

2024-07-31 17:02 UTC, forestkeeper approved these changes

2024-07-31 17:20 UTC, merged