Fix less than operator for binary datatype
babelfish-for-postgresql/babelfish_extensions pull request #2812
Opened 2024-07-31 09:24 UTC by sumitj824

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-31 09:47 UTC, KushaalShroff requested changes

2024-07-31 09:47 UTC, KushaalShroff commented on contrib/babelfishpg_common/sql/binary.sql
> -AS 'babelfishpg_common', 'varbinary_eq'
Wow, how did we not catch this?

2024-07-31 10:16 UTC, sumitj824 commented on contrib/babelfishpg_common/sql/binary.sql
> -AS 'babelfishpg_common', 'varbinary_eq'
We don't have operator-related test coverage for almost all data types.

2024-07-31 14:29 UTC, shah-nirmit approved these changes
LGTM

2024-07-31 17:15 UTC, forestkeeper approved these changes, later dismissed
LGTM

2024-08-02 06:43 UTC, KushaalShroff approved these changes

2024-08-02 08:22 UTC, merged