Fix the JDBC timeout error in release mode
babelfish-for-postgresql/babelfish_extensions pull request #290
Opened 2022-06-20 05:00 UTC by shalinilohia50

Moving the variable old_db_name out of try block. It was leading to
segmentation fault in the release mode.

Task: BABEL-3077
Signed-off-by: Shalini Lohia <lshalini@amazon.com>

2022-06-20 06:27 UTC, surendravishnoi requested changes
Please add more details to commit message.

2022-06-21 12:44 UTC, shalinilohia50 commented
> 

Updated the commit message.

2022-06-24 06:18 UTC, surendravishnoi approved these changes

2022-06-24 09:42 UTC, kuntalghosh approved these changes

2022-06-24 09:43 UTC, merged