fix to show brackets while storing a procedure in babelfish catalog
babelfish-for-postgresql/babelfish_extensions pull request #3017
Opened 2024-10-12 12:26 UTC by pranavJ23

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-15 12:11 UTC, tanscorpio7 requested changes

2024-10-15 12:11 UTC, tanscorpio7 commented on test/JDBC/expected/alter-function-vu-verify.out
> +alter_func_f2#!#SQL#!#ALTER function alter_func_f2(@param2 varchar(10)) returns varchar(10) begin return @param2 end<newline>
This does not look expected

2024-10-16 16:40 UTC, tanscorpio7 requested changes

2024-10-16 16:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +		execsql->original_query = pstrdup(result.c_str());
Lets not pstrdup here, instead pass a duplicate copy of the string in `handleBatchLevelStatement`.

2024-10-16 16:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +		execsql->original_query = pstrdup(result.c_str());
We can put this code into another function to avoid duplicate code

2024-10-18 06:51 UTC, shalinilohia50 commented on test/JDBC/expected/BABEL_OBJECT_DEFINITION_before_16_5-vu-prepare.out
> +-- Table-valued function
Please add test for multi line comments.

2024-10-18 06:54 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +createHandlingForBatchLevelStatement(TSqlParser::Batch_level_statementContext *ctx, const char *originalQuery)
Please rename it to something meaningful like `storeOriginalQueryForBatchLevelStatement`.

2024-10-18 06:57 UTC, shalinilohia50 commented on test/JDBC/expected/BABEL_OBJECT_DEFINITION_before_16_5-vu-prepare.out
> +CREATE FUNCTION object_definition_fc1(@fc1_a nvarchar) RETURNS nvarchar AS BEGIN return @fc1_a END;
Let's add test where the datatype is within the brackets like `[varchar]`.

2024-10-18 08:22 UTC, tanscorpio7 approved these changes
Please add all the test cases mentioned in all three JIRAs to JDBC & DDL framework.

2024-10-18 10:56 UTC, shalinilohia50 commented
1. Let's add tests in DDL framework as well for single/multi line comments and brackets around the datatype.
2. Please don't create another test file(storeOriginalQuery*) just to show function object definition, rather use the existing ones(BABEL_OBJECT_DEFINITION*).

2024-10-18 14:12 UTC, tanscorpio7 approved these changes

2024-10-18 14:19 UTC, shalinilohia50 approved these changes

2024-10-19 11:52 UTC, shalinilohia50 approved these changes

2024-10-21 06:43 UTC, tanscorpio7 approved these changes

2024-10-21 17:16 UTC, HarshLunagariya approved these changes

2024-10-21 17:16 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/tsqlIface.cpp
> +		return pstrdup(originalQueryCopy.c_str());
nit:
We can refactor it by moving following 3 lines out of if ... else.
```
endIndex = startIndex + 5;
originalQueryCopy.replace(startIndex, endIndex - startIndex, "CREATE");
return pstrdup(originalQueryCopy.c_str());
```

2024-10-22 08:55 UTC, surendravishnoi submitted a review, later dismissed

2024-10-22 12:20 UTC, shardgupta approved these changes

2024-10-22 12:23 UTC, merged