[OSS ONLY] Fix to throw error instead of warning in JDBC test logfile
babelfish-for-postgresql/babelfish_extensions pull request #3161
Opened 2024-11-25 13:27 UTC by pranavJ23

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-01-21 16:31 UTC, tanscorpio7 requested changes

2025-01-21 16:31 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						if (proctup == NULL)
we should use `HeapTupleIsValid` & curly braces can be removed in next line.

2025-01-21 16:31 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						    ReleaseSysCache(proctup);
In case of error we do not need to release syscache

2025-01-25 11:50 UTC, tanscorpio7 requested changes

2025-01-25 11:50 UTC, tanscorpio7 commented on .github/workflows/jdbc-tests.yml
> +          grep -i "WARNING:.*leak" ~/psql/data/logfile | sed -E 's/^.*WARNING:\s*([^:]+(\s+reference\s+leak|connection leak)[^:]*):.*/WARNING:  \1/' | sort  > actual-leak-warnings.out
Some warnings do not contain the word leak but are still important for us & need to be resolved.
For example `elog(WARNING, "snapshot %p still active", active);`
Will this check be able to catch this WARNING if it comes up in future ?

2025-01-25 12:20 UTC, pranavJ23 commented on .github/workflows/jdbc-tests.yml
> +          grep -i "WARNING:.*leak" ~/psql/data/logfile | sed -E 's/^.*WARNING:\s*([^:]+(\s+reference\s+leak|connection leak)[^:]*):.*/WARNING:  \1/' | sort  > actual-leak-warnings.out
To grep the warnings which do not contains leak, we need to either grep only "WARNING" or we need to grep the whole line containing "WARNING" keyword. 
If we only grep WARNING in the expected-file then while debugging it might be difficult to tell that which type of new warning we are getting.
If we grep whole line containing "WARNING" then there are some reference tuple which might be dynamically allocated during test run, so we cannot compare the expected and actual files.
Open to suggestions!

2025-01-28 16:28 UTC, tanscorpio7 approved these changes

2025-01-29 05:02 UTC, sumitj824 commented on contrib/babelfishpg_tsql/src/pltsql_ruleutils.c
> +		ReleaseSysCache(proctup);
There is one more PG_RETURN_NULL() at line 528, we need to release sys cache there as well.

2025-01-29 05:02 UTC, sumitj824 commented on .github/workflows/jdbc-tests.yml
> +          LOG_FILE=~/psql/data/logfile
Lets have bash script to this check and you can invoke that directly.

2025-01-29 05:07 UTC, sumitj824 commented on .github/workflows/jdbc-tests.yml
> +          fi
Does this mean that for any new testfile which will generate warnings that are expected will increase this count? And everytime developer needs to update this?

2025-01-29 05:08 UTC, pranavJ23 commented on .github/workflows/jdbc-tests.yml
> +          fi
Yes if that generates the LEAK or SNAPSHOT warning then only this count will change

2025-02-03 04:10 UTC, sumitj824 approved these changes

2025-02-13 17:13 UTC, shardgupta approved these changes

2025-02-13 17:14 UTC, merged