Babel 5341 4 x
babelfish-for-postgresql/babelfish_extensions pull request #3236
Opened 2024-12-11 12:54 UTC by Yvinayak07

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-23 09:55 UTC, KushaalShroff requested changes

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
Do we have test cases for them? Can you explain their need?

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		func_oid == FLOAT8_NUMERIC ||
Should we also consider these cast functions:
```
1> select typname from pg_type where oid in (select castsource from pg_cast where casttarget = 1700)
2> go
typname                                                                                                                                                                                                                                                         
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
int8                                                                                                                                                                                                                                                            
int2                                                                                                                                                                                                                                                            
int4                                                                                                                                                                                                                                                            
float4                                                                                                                                                                                                                                                          
float8                                                                                                                                                                                                                                                          
money                                                                                                                                                                                                                                                           
numeric                                                                                                                                                                                                                                                         
jsonb                                                                                                                                                                                                                                                           
fixeddecimal                                                                                                                                                                                                                                                    
varchar                                                                                                                                                                                                                                                         
bit                                                                                                                                                                                                                                                             
sql_variant 
```

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +is_convertable_to_numeric(Oid func_oid)
Lets add comments on top to describe the need of this util function

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		elog(ERROR, "cache lookup failed for function %u", func_oid);
1. Lets do this conditionally since for all of the cast functions except money ones do not require lookup.
2. Even for looking up for money cast function, we can cache the oid in a static variable so a so to reuse it. For example:
```
static Oid fixeddecimal_numeric_oid = InvalidOid;

fixeddecimal_numeric_oid_func()
if (fixeddecimal_numeric_oid == InvalidOid):
     find the oid of fixeddecimal_numeric function
else return fixeddecimal_numeric_oid
```
and then we can use this helper function directly inside the if condition like:
```
func_oid == fixeddecimal_numeric_oid_func()
```
This will have 2 look ups, but thinking of larger picture where this function gets called n times then this approach gives us O(2) complexity rather than O(n)

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if ((!(con->consttype == INT4OID) && !is_numeric_datatype(con->consttype)) ||
What about bigint, smallint, tinyint. Also bit?

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +					if (!plan && con->consttype == INT4OID)
Lets add comments for the conditions we have added

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				const SubLink *sublink = (const SubLink *) expr;
comment with /* Copied from exprTypmod. */

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +			 !utilptr->is_tsql_decimal_datatype(common_type) &&
Lets check the need of this

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +			result_typmod = -1;
Lets name this as numeric_result_typmod

2024-12-23 09:55 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +				Plan* temp = NULL;
Why do we need temp?

2024-12-24 15:14 UTC, rohit01010 requested changes

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if (!plan &&
NIT: rewrite `!plan` to `plan == NULL`

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/include/tds_response.h
> +extern bool is_numeric_cast(Oid func_oid);
if is `is_numeric_cast` function is not being used in anywhere else, kindly mark it as static.

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 */
kindly update the comment to explain the checks in the if condition.

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if (plan && var->varno == OUTER_VAR)
How are we ensuring that `if plan is NULL then it is called from TSQL and not from TDS` ?

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +					}
When plan is `NOT NULL` i.e. function is not called from TSQL extension then shouldn't we return `-1`, as we use to do previously ?

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		nspoid = get_namespace_oid("sys", true);
we should keep the second parameter as `false` which will ensure that if `get_namespace_oid` function is unable to find oid of `sys` then we should throw error.

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_bit_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("bit2numeric")), 1, funcargtypes, true);
should we also consider setting the `missing_ok` parameter value as `false` ?

2024-12-24 15:14 UTC, rohit01010 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define I4TOI2 314
These Oids are already defined in `fmgroids.h` header file, we can directly use those constants.

2024-12-24 15:14 UTC, rohit01010 commented on test/JDBC/expected/BABEL-CASE_EXPR-vu-verify.out
> +   WHEN 3 THEN CAST(1234567.8901234567890 AS BigNumericType_BABEL_5341)
kindly use 18 digits before decimal for value with type `BigNumericType_BABEL_5341`, so result precision can also be verified.

2024-12-25 05:56 UTC, Deepesh125 requested changes

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
what if OID gets changed tomorrow due to addition of cast or other object?

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		nspoid = get_namespace_oid("sys", true);
you can cache this by making it static/extern and use it everywhere

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_bit_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("bit2numeric")), 1, funcargtypes, true);
missing_ok is passed as true which means it may return invalid oid. We should detect that and throw an error. IMO, we should pass missing-ok = false

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
what is meaning of these INT48, INT84 etc?

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if ((!(con->consttype == INT4OID) && !is_numeric_datatype(con->consttype)) ||
IIRC, const node can have int4, numeric, bool or unknown/text oid. so we probably need to think about bool/bit for tsql

2024-12-25 05:56 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 * from tds side. Here we make resursive call so as to calculate
can you please explain meaning of "tds side"?

2024-12-25 05:56 UTC, Deepesh125 commented on test/JDBC/input/NUMERIC_TYPMOD.sql
> +GO
these test cases are simple in terms of typmod. can you add cases where we can test boundaries of typmod? (38,0), (38,38), etc?

2024-12-25 05:56 UTC, Deepesh125 commented on test/JDBC/input/BABEL-CASE_EXPR-vu-prepare.sql
> +CREATE VIEW BABEL_5341_V1 AS
in verify part, we should check the precision, scale of the column using some system metadata views

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if ((!(con->consttype == INT4OID) && !is_numeric_datatype(con->consttype)) ||
FOR:

1. bigint we have INT8_NUMERIC
2. tinyint  we have INT2_NUMERIC
3.smallint we have I4TOI2
4. bit we have is_tsql_bit_numeric

So these will be converted to int or numeric. and get handled in these conditions.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		func_oid == FLOAT8_NUMERIC ||
Added most of these that could be castable to numeric.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +is_convertable_to_numeric(Oid func_oid)
Added comment, resolved.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		elog(ERROR, "cache lookup failed for function %u", func_oid);
As suggested made helper functions for:

1. bit2numeric
2. fixeddecimal_numeric
3. numeric_fixeddecimal
4. int4bit

stored their Oid in a static variable.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +					if (!plan && con->consttype == INT4OID)
added comment for explanation, resolved.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				const SubLink *sublink = (const SubLink *) expr;
added comment /* Copied from exprTypmod. */ for both T_SubLink and T_CoerceToDomain.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +			 !utilptr->is_tsql_decimal_datatype(common_type) &&
We need decimal type, if all the branches are of decimal type then its common type is decimal.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +			result_typmod = -1;
renamed result_typmod to numeric_result_typmod

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tsql/src/pltsql_coerce.c
> +				Plan* temp = NULL;
I used for testing purpose, removed the variable temp.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
We have existing test cases for INT48 conversions. As a precautionary measure, we have included OIDs for all integer type casts to ensure comprehensive coverage.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
Added comment on above of these OID's used.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if (!plan &&
changed to plan == NULL. Resolved.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/include/tds_response.h
> +extern bool is_numeric_cast(Oid func_oid);
Marked as static. resolved.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 */
Updated the comments to explain this condition point wise.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +					}
Yes, we need to add that condition we missed that here. added this condition here resolved.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		nspoid = get_namespace_oid("sys", true);
changed the parameter to false so as we can throw error if oid is not found.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_bit_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("bit2numeric")), 1, funcargtypes, true);
changed the parameter to false so as we can throw error if oid is not found.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define I4TOI2 314
Picked Oid's from fmgroids.h so if Oid's change in future we need to change at one place.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
We have picked the Oid's from fmgroids.h so in future if Oid's change we need to make change at one place. If we do lookup from catalog it will increase time.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		nspoid = get_namespace_oid("sys", true);
Made a static variable sys_nspoid for getting oid for sys.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_bit_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("bit2numeric")), 1, funcargtypes, true);
changed the parameter 'missing_ok' to false so as we can throw error if oid is not found.

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 * from tds side. Here we make resursive call so as to calculate
When 'plan' is NULL, it means we're calling this function from the Babelfish TSQL extension not tds( Resolved with correct comment). In this case, we don't have a query plan to work with.

2025-01-01 05:34 UTC, Yvinayak07 commented on test/JDBC/input/NUMERIC_TYPMOD.sql
> +GO
Added in BABEL-CASE_EXPR-verify file:
- https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/3236/files#diff-d8342fa5f1c401e85f0a2c76f761031caed3e894ea483b9c12b53c8b2a20b098R13619
- https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/3236/files#diff-d8342fa5f1c401e85f0a2c76f761031caed3e894ea483b9c12b53c8b2a20b098R14506

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +#define INT82 714
- We have picked the Oid's from fmgroids.h so in future if Oid's change we need to make change at one place. If we do lookup from catalog it will increase time.

- INT48 and INT84 are casting functions. INT48 represents a cast from INT4 (4-byte integer) to INT8 (8-byte integer), while INT84 represents the reverse cast from INT8 to INT4.

2025-01-01 05:34 UTC, Yvinayak07 commented on test/JDBC/expected/BABEL-CASE_EXPR-vu-verify.out
> +   WHEN 3 THEN CAST(1234567.8901234567890 AS BigNumericType_BABEL_5341)
```
-- BBF After Our build.
SELECT CASE 4
   WHEN 1 THEN CAST(12345.6789 AS NUMERIC(20,2))
   WHEN 2 THEN CAST(98765.4321 AS DECIMAL(18,4))
   WHEN 3 THEN CAST(1234567.8901234567890 AS NUMERIC(38,10))
   WHEN 4 THEN CAST(99.99 AS DECIMAL(5,2))
   ELSE CAST(0 AS NUMERIC(20,2))
END AS RESULT

RESULT                                  
----------------------------------------
                           99.9900000000
```

```
-- SQLserver 
SELECT CASE 4
   WHEN 1 THEN CAST(12345.6789 AS NUMERIC(20,2))
   WHEN 2 THEN CAST(98765.4321 AS DECIMAL(18,4))
   WHEN 3 THEN CAST(1234567.8901234567890 AS NUMERIC(38,10))
   WHEN 4 THEN CAST(99.99 AS DECIMAL(5,2))
   ELSE CAST(0 AS NUMERIC(20,2))
END AS RESULT

RESULT                                  
----------------------------------------
                           99.9900000000

```

2025-01-01 05:34 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				if ((!(con->consttype == INT4OID) && !is_numeric_datatype(con->consttype)) ||
- When a expression is of bit it enter T_Funcexpr and call it recursively with bit2numeric and solve the typmod.
```
test case: 

SELECT CASE 
    WHEN 1 = 1 THEN 
        CASE 
            WHEN 1=1
            THEN CAST(1234.56 AS NUMERIC(10,2)) * cast(1 as bit)
            ELSE CAST(9876.54 AS numeric(12,2)) / cast(1 as bit)
        END
    ELSE CAST(0 AS DECIMAL(12,2))
END AS result;
```

-  The bit data type is used for storing Boolean values.

2025-01-01 05:34 UTC, Yvinayak07 commented on test/JDBC/input/BABEL-CASE_EXPR-vu-prepare.sql
> +CREATE VIEW BABEL_5341_V1 AS
Added test cases related to this.

2025-01-01 06:37 UTC, rohit01010 approved these changes

2025-01-01 08:49 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		func_oid == FLOAT8_NUMERIC ||
does it mean we will have to update IF condition whenever we introduce new cast (xyz -> numeric)? it will have maintenance issue

2025-01-01 09:05 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 * 1) plan == NULL means we are invoking this function from babelfishpg_tsql extension.
or we can say, during parsing phase

2025-01-01 09:07 UTC, Deepesh125 submitted a review, later dismissed

2025-01-01 09:32 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +				 * 1) plan == NULL means we are invoking this function from babelfishpg_tsql extension.
updated the comment. Resolved

2025-01-07 10:16 UTC, KushaalShroff requested changes

2025-01-07 10:16 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		typoid = GetSysCacheOid2(TYPENAMENSP, Anum_pg_type_oid, CStringGetDatum("bit"), ObjectIdGetDatum(sys_nspoid));
For sanity we should always check if (sys_nspoid == InvalidOid) and assign it before using it.

2025-01-07 10:16 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_fixeddecimal_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("fixeddecimal_numeric")), 1, funcargtypes, true);
Can we lookup in pg_cast instead?
```
	tuple = SearchSysCache2(CASTSOURCETARGET,
							ObjectIdGetDatum(typeId),
							ObjectIdGetDatum(typeId));

	if (HeapTupleIsValid(tuple))
	{
		Form_pg_cast castForm = (Form_pg_cast) GETSTRUCT(tuple);

		*funcid = castForm->castfunc;
		ReleaseSysCache(tuple);
	}
```
Seems cleaner and faster

2025-01-07 15:03 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		typoid = GetSysCacheOid2(TYPENAMENSP, Anum_pg_type_oid, CStringGetDatum("bit"), ObjectIdGetDatum(sys_nspoid));
Made this sanity check.

2025-01-07 15:03 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +		tsql_fixeddecimal_numeric_oid = LookupFuncName(list_make2(makeString("sys"), makeString("fixeddecimal_numeric")), 1, funcargtypes, true);
Lookup done in pg_cast for faster access.

2025-01-07 18:32 UTC, KushaalShroff requested changes

2025-01-07 18:32 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +func_oid_of_cast_from_source_target(Oid castsource, Oid casttarget)
Why cant we have the same naming convention: LookupCastFuncName

2025-01-07 18:32 UTC, KushaalShroff commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +	if (OidIsValid(sys_nspoid))
By my comment earlier I didnt mean to add the valid check like this. Here it would be obvious that sys_nspoid is valid.

What I meant was coding it this way:
```
if (!OidIsValid(sys_nspoid))
	sys_nspoid = get_namespace_oid("sys", false);
```

2025-01-08 05:17 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +func_oid_of_cast_from_source_target(Oid castsource, Oid casttarget)
Replaced func_oid_of_cast_from_source_target -> LookupCastFuncName.

2025-01-08 05:17 UTC, Yvinayak07 commented on contrib/babelfishpg_tds/src/backend/tds/tdsresponse.c
> +	if (OidIsValid(sys_nspoid))
Corrected, I thought it other way.
Resolved

2025-01-08 08:20 UTC, KushaalShroff approved these changes

2025-01-08 09:02 UTC, merged