Performance Improvement of create login in BBF
babelfish-for-postgresql/babelfish_extensions pull request #3291
Opened 2024-12-20 04:13 UTC by anju15bharti

### Description

[Describe what this change achieves - Guidelines below (please delete the guidelines after writing the PR description)]

> 1. *What* is the change? This is best described in terms of “Currently, Babelfish does X. With this change it now does Y.” Think of “What *did* it *used* to do?” and “What *does* it do *now*?”
2. *Why* was the change made? What drove our desire to put effort into the change?
3. *How* was the code changed should only appear for large commits. This can serve as a rough roadmap to what’s contained in the commit. It should be very high level; if it’s directly referencing code it’s probably too detailed. It’s also critical that this section of a commit message does not try to replace proper code documentation (ie, block comments or README files). Generally, this section should only appear if the commit itself is large enough that it’s helpful to provide a roadmap to someone looking at the commit.
4. The last descriptive piece is the “title” for the commit: the very first line of the commit message, which should typically be less than 80 characters. A good title is *critical*, because it’s the only thing that shows up in places like the Github commit listing. No one’s got time to read through full commit messages when trying to find a single commit out of dozens.

### Issues Resolved

[List any issues this PR will resolve]

### Test Scenarios Covered ###
* **Use case based -**

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-01-02 05:07 UTC, tanscorpio7 requested changes

2025-01-02 05:07 UTC, tanscorpio7 commented on test/JDBC/expected/db_securityadmin-vu-verify.out
> +-- Wait to sync with another session
better to use the terminate conn flag

2025-01-02 05:08 UTC, tanscorpio7 requested changes

2025-01-02 05:08 UTC, tanscorpio7 commented on test/JDBC/input/test_windows_login-vu-prepare.mix
> +-- sla 55000
let us also merge this fix in 17.2 & 16.7. This will help us skip creating before and after files for this test case.

2025-01-02 05:32 UTC, anju15bharti commented on test/JDBC/expected/db_securityadmin-vu-verify.out
> +-- Wait to sync with another session
Since we have terminated the process from psql endpoint already in this testfile just waiting time was missing. So I think for terminating from psql endpoint, we can go with this fix for now and if we want to fix this thoroughly, respective author can do it later.

2025-01-02 05:34 UTC, anju15bharti commented on test/JDBC/input/test_windows_login-vu-prepare.mix
> +-- sla 55000
We will still need to create before file for version before 16.7.

2025-01-02 05:56 UTC, tanscorpio7 approved these changes

2025-01-02 08:48 UTC, HarshLunagariya requested changes

2025-01-02 08:48 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/catalog.c
> +	}
Here, we are relying on the fact that bbf_role_admin is always be the direct member of every TSQL login/user/role. Is there a possibility to have an exception?
One suggestion to add testcase which validates all the role entries of babelfish_authid_user_ext and babelfish_authid_login_ext to validate whether they are member of bbf_role_admin with admin option or not.

2025-01-02 09:11 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +	}
It can be possible if do some grants from psql endpoint but that is then interoperability case.
And even in this case, it will fall back to earlier path of iterating through all of it's member.

We rely on the fact that in bbf we grant all roles to bbf_role_admin. Will add testcase explicitly to validate the same.

2025-01-02 12:54 UTC, HarshLunagariya approved these changes

2025-01-03 11:56 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/catalog.c
> +bbf_check_member_has_direct_priv_to_grant_role(Oid member, Oid role)
this hook is critical as it overrides admin role membership. Please make sure we have test case for each use case which should return true and false from this function.

2025-01-03 11:56 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/catalog.c
> +	memlist = SearchSysCacheList2(AUTHMEMROLEMEM,
we are checking two things
1) bbf admin is member of "role"
2) membership is with admin option ON

do we have a use case where this not true for bbf_admin and bbf_roles? if not, it might be sufficient to check for role being bbf_role (assuming that check is very fast to do)

2025-01-03 12:09 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +	memlist = SearchSysCacheList2(AUTHMEMROLEMEM,
No, for every bbf_roles, these conditions will be true. I checked `is_babelfish_role` API is costlier than the current approach since it uses `roles_is_member_of` API internally to find all memberships.

2025-01-03 13:40 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +bbf_check_member_has_direct_priv_to_grant_role(Oid member, Oid role)
This hook will always return true for valid scenario if member is bbf_role_admin and dialect is tsql and In BBF for all scenarios through which we hit this hook(i.e create/alter role and create database) we set bbf_role_admin as current user before execution so it is ought to return true in every bbf session valid case.
In order to add negative testcases for this hook we need to add scenarios of grant roles from psql endpoint which already exists in bbf https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/BABEL_4_X_DEV/test/JDBC/expected/db_securityadmin-vu-verify.out#L1164.

2025-01-06 09:03 UTC, surendravishnoi commented on contrib/babelfishpg_tsql/src/catalog.c
> +	for (int i = 0; i < memlist->n_members; i++)
let us not assume that memlist will be non-null, we should check for it and fallback to PG in case of null

2025-01-06 11:57 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +	for (int i = 0; i < memlist->n_members; i++)
`SearchCatCacheList` inside `SearchSysCacheList2` ensures that memlist value should be not null as it allocates memory to memlist even if no entry matches in the search and assign memlist->n_members as 0.

2025-01-06 12:02 UTC, surendravishnoi approved these changes

2025-01-06 15:07 UTC, merged