fix the bug instead of trigger behaves wrongly in recursively call
babelfish-for-postgresql/babelfish_extensions pull request #333
Opened 2022-06-27 20:11 UTC by forestkeeper

recursively call the instead of trigger may lose the last DML to the triggered table

in previous impl, recursively trigger a instead of trigger will not do any
changes into the triggered table, as for the last triggered DML, it
shouldn't do the instead of procedure, what it should do is to do DML in
the table, since the last DML in a recursive trig chain should not
trig it's trigger

Task: BABEL-3115 & BABEL-3116 & BABEL-3118
Signed-off-by: Zhibai Song <szh@amazon.com>

### Description

Row inserted by an INSTEAD-OF INSERT trigger is missing in the example below: 

```
-- repro in Babelfish:
1>
2> CREATE TABLE t
3> (
4> c1 int IDENTITY(1,1) PRIMARY KEY,
5> c2 varchar(20) UNIQUE,
6> );
7>
8> INSERT INTO t(c2)
9> VALUES ('Joe'), ('Steve');
10>
11>
12> SELECT * FROM t
13> GO
c1          c2
----------- --------------------
          1 Joe
          2 Steve
1>
2> CREATE TRIGGER TR_t ON t
3> INSTEAD OF INSERT
4> AS
5>  DECLARE @c1 int, @c2 varchar(20)
6> SELECT @c1 = c1, @c2 = c2 FROM inserted
7> INSERT INTO t (c2) VALUES(@c2 + '2') --BUG: This INSERT disappears
8> GO
1>
2> INSERT INTO t(c2) VALUES ('Joe')
3> GO
1>
2> --There should be 3 rows, but there are only 2 rows. The INSERT from the trigger is lost.
3> SELECT * FROM t
4> GO
c1          c2
----------- --------------------
          1 Joe
          2 Steve
```
Explanation: 
- Insert inside instead of trigger causes a recursive trigger execution
- A recursive trigger execution is capped at nesting level of one and should be a no-op.
- We skip both DML and trigger execution but we should execute the original DML as trigger is a no-op.

The same problem will happen for Delete/Update as well.

### Issues Resolved

The fix identifies a recursive instead of trigger and does not skip the DML execution
 

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-27 22:15 UTC, nasbyj requested changes
Please improve the commit message

2022-06-29 06:50 UTC, kuntalghosh approved these changes, later dismissed

2022-06-29 06:50 UTC, kuntalghosh reviewed
Please don't check-in with the logfile.

2022-06-29 07:18 UTC, surendravishnoi requested changes
Please remove log file and improve commit message

2022-06-29 07:27 UTC, kuntalghosh commented
This PR also removes the unnecessary logfile. Once #337 is merged, we just need to resolve the conflict. But, we should improve the commit message.

2022-06-29 17:42 UTC, forestkeeper commented
I have updated my commit msg

2022-06-29 18:33 UTC, surendravishnoi approved these changes, later dismissed

2022-06-29 20:59 UTC, nasbyj requested changes, later dismissed

2022-06-29 20:59 UTC, nasbyj commented on contrib/babelfishpg_tsql/src/hooks.c
> + *  have to add a hook into Manfred code to callback into babel code,
Should not be refering to Manfred in public commits

2022-06-29 20:59 UTC, nasbyj commented on contrib/babelfishpg_tsql/src/hooks.c
> +		&& resultRelInfo->ri_TrigDesc!=NULL
`!=` should be wrapped in spaces

2022-06-29 20:59 UTC, nasbyj commented on contrib/babelfishpg_tsql/src/hooks.c
> +			for (i =0; i<resultRelInfo->ri_TrigDesc->numtriggers; ++i){
extra space before `=0`

2022-06-29 20:59 UTC, nasbyj commented on contrib/babelfishpg_tsql/src/hooks.c
> + *  the function will depend on PLtsql_execstate to find whether
Should also describe what the function is actually doing... something along the lines of "Returns true if we are about to execute an INSTEAD OF trigger that has already been executed."

2022-06-29 22:23 UTC, nasbyj reviewed
LGTM, but not marking approved since I'm not an expert on the code.

2022-06-30 03:37 UTC, macwoody reviewed
why does your change prints additional row count in the result ?

2022-06-30 04:18 UTC, forestkeeper commented
It's because this behavior is different from PG

2022-06-30 04:58 UTC, surendravishnoi approved these changes

2022-06-30 04:59 UTC, kuntalghosh approved these changes

2022-06-30 05:01 UTC, merged