Remove unneeded logfile from repo
babelfish-for-postgresql/babelfish_extensions pull request #337
Opened 2022-06-28 11:10 UTC by reshke

### Description
Hi, i have noticed that there is logfile commited in #319 , which is just a dev log and unneeded i think
[Describe what this change achieves]
 
### Issues Resolved

[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-28 11:45 UTC, reshke commented
test failed for some reason, but default branch also red in ci

2022-06-29 06:16 UTC, kuntalghosh approved these changes, later dismissed

2022-06-29 07:01 UTC, surendravishnoi requested changes
tests are failing, please validate and put a comment that they are all known, also commit message should be better

2022-06-29 07:29 UTC, reshke commented
> tests are failing, please validate and put a comment that they are all known, also commit message should be better
Hi surendravishnoi, thank you for review, i changed commit message, adding some details about my chanages. Also i checked failed tests and they are just the same failled tests, as in default branch (BABEL_2_X_DEV) right now

2022-06-29 08:26 UTC, surendravishnoi approved these changes

2022-06-29 11:30 UTC, kuntalghosh approved these changes

2022-06-29 11:32 UTC, merged