Bsrohan dev
babelfish-for-postgresql/babelfish_extensions pull request #377
Opened 2022-07-11 10:13 UTC by basasairohan

### Description

Added test scripts for system functions in prepare-verify format. 
 
Signed-off-by: Sai Rohan Basa [bsrohan@amazon.com](mailto:bsrohan@amazon.com)

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-11 11:41 UTC, surendravishnoi requested changes
there is two ways to make object names unique for MVU
1) Create each object in its own DB and use any name
2) Create object in default DB but use unique object name

I would prefer to use 2. To do that, simple approach is to have filename_objname as object name. So t1 in objectpropertyex-vu-prepare becomes objectpropertyex-vu-prepare-t1

2022-07-11 17:31 UTC, surendravishnoi commented on test/JDBC/expected/sys-trigger_nestlevel-vu-prepare.out
> +CREATE TABLE t1(c1 int)
we are still using simple object names? we should use sys-triggger_nestlevel-vu-prepare-t1

2022-07-12 08:06 UTC, surendravishnoi approved these changes

2022-07-12 11:39 UTC, kuntalghosh approved these changes

2022-07-12 11:45 UTC, merged