Support TSQLs Information_schema_tsql.constraint_column_usage view
babelfish-for-postgresql/babelfish_extensions pull request #391
Opened 2022-07-13 14:21 UTC by anju15bharti

We have supported TSQLs Information_schema_tsql.constraint_column_usage view.

Signed-off-by: Anju Bharti <abanju@amazon.com>

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-14 08:38 UTC, HarshLunagariya requested changes
Please add testcase for cross schema foreignkeys.

2022-07-14 17:01 UTC, shalinilohia50 submitted a review, later dismissed

2022-07-14 17:03 UTC, sangilsong submitted a review, later dismissed

2022-07-15 03:34 UTC, HarshLunagariya submitted a review, later dismissed

2022-07-15 05:30 UTC, surendravishnoi submitted a review, later dismissed

2022-07-15 18:22 UTC, shalinilohia50 approved these changes

2022-07-17 15:16 UTC, surendravishnoi approved these changes

2022-07-18 07:45 UTC, HarshLunagariya approved these changes

2022-07-18 10:51 UTC, kuntalghosh approved these changes

2022-07-18 11:17 UTC, merged