Fixed template information (version and extensions fields)
babelfish-for-postgresql/babelfish_extensions pull request #45
Opened 2021-12-01 16:15 UTC by 3manuek

### Description

Fixed incorrect template references for version/extension.

 
### Issues Resolved

No issues related.

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-02 16:18 UTC, nasbyj commented on .github/ISSUE_TEMPLATE/enhancement.yaml
> +      description: What extension contrib of our software are you running?
We should actually remove this from the enhancement template; we should decide what extension a feature request affects.

2021-12-02 16:18 UTC, nasbyj commented on .github/ISSUE_TEMPLATE/question.yaml
> +  - type: dropdown
Also not relevant for questions.

2021-12-03 18:11 UTC, nasbyj requested changes

2021-12-03 18:11 UTC, nasbyj commented on .github/ISSUE_TEMPLATE/question.yaml
> +  - type: dropdown
Please remove this chunk as well.

2021-12-03 18:12 UTC, nasbyj commented on .github/ISSUE_TEMPLATE/question.yaml
> +  - type: dropdown
Nevermind, version here makes sense.

2021-12-03 18:12 UTC, nasbyj submitted a review, later dismissed

2021-12-07 16:14 UTC, gopinathpai approved these changes, later dismissed
looks good to me

2022-01-13 18:37 UTC, susanmdouglas-aws commented on .github/ISSUE_TEMPLATE/bug.yaml
>        value: "A bug happened!"
I think we discussed removing the 'value' content, but if I misunderstood, can we replace 'A bug happened!' with:

Tell us about the bug.

I'd rather have that line repeated twice than sound too excited about a bug...

2022-01-18 16:10 UTC, nasbyj commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      description: If known, what extension is the problem occurring with?
s/what/which/

2022-02-22 16:41 UTC, susanmdouglas-aws approved these changes

2022-05-17 15:58 UTC, 3manuek commented
@nasbyj @susanmdouglas-aws I reopened this PR into a new one from a personal fork as requested: https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/205. We can probably close this one.

2022-05-17 16:44 UTC, closed without merging