feat: quick install scripts
babelfish-for-postgresql/babelfish_extensions pull request #50
Opened 2021-12-10 17:52 UTC by xaviersierra

### Description

Provides scripts for quick installing babelfish
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-12-13 16:23 UTC, nasbyj requested changes
Haven't done a full review yet, but please add an appropriate reference to the install instructions to `/README.md`

2021-12-16 15:48 UTC, 3manuek submitted a review, later dismissed

2022-01-10 16:26 UTC, susanmdouglas-aws commented on install/README.md
> +The are some environment variable that can be set in order to customize the installation script.
How about:

You can use environment variables to customize the installation script:

2022-01-10 16:29 UTC, susanmdouglas-aws commented on install/README.md
> +Currently the supported linux distribution for this script are:
How about:

This directory contains scripts that install Babelfish for PostgreSQL.  Select the install.sh script for your Linux platform to install Babelfish on your system. 

Currently the supported Linux distributions are:

2022-01-10 16:31 UTC, susanmdouglas-aws commented on install/README.md
> +- Debian bullseye
The Debian website capitalizes Bullseye...

2022-01-11 15:41 UTC, 3manuek commented
WIP tasks:

- Adding docker environments to serve as a test environment for the installation scripts.
- Documenting the test procedure.

cc/ @gopinathpai @nasbyj

2022-05-19 17:24 UTC, closed without merging