TRY_CONVERT to datetime2 causes NULL return
babelfish-for-postgresql/babelfish_extensions pull request #712
Opened 2022-10-19 22:32 UTC by Jakeowen1

Currrently, Babelfish returns NULL when a user calls TRY_CONVERT to convert a datatype to a datetime2. This commit enables TRY_CONVERT to behave correctly with the datetime2 datatype. This commit also updates tests from BABEL-3486 with the correct expected output for TRY_CONVERT calls with datetime2

Task: BABEL-3614
Signed-off-by: Jake Owen <owjco@amazon.com>

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-25 14:32 UTC, Jakeowen1 commented on test/python/expected/upgrade_validation/expected_dependency.out
> +Function sys.babelfish_try_conv_to_datetime2(anyelement)
TODO: Add tests that remove these functions from expected_dependency.out

2022-10-25 21:56 UTC, AvantikaDG requested changes

2022-10-25 21:56 UTC, AvantikaDG commented on contrib/babelfishpg_tsql/sql/sys_function_helpers.sql
> +-- convertion to datetime2
nit: typo - should be "conversion"

2022-10-25 21:56 UTC, AvantikaDG commented on contrib/babelfishpg_tsql/src/backend_parser/gram-tsql-epilogue.y.c
> +	else if (strcmp(typename_string, "datetime2") == 0)
Can we use the type_oid to check the type like in the datetime check?

Something like `else if (type_oid == typenameTypeId(NULL, makeTypeName("datetime2")))`

2022-10-25 21:56 UTC, AvantikaDG commented on contrib/babelfishpg_tsql/src/backend_parser/gram-tsql-epilogue.y.c
> +		if(typmod == NULL || typmod < 0)
Can you add a comment that default precision for fractional seconds is 7 digits?

2022-10-25 21:56 UTC, AvantikaDG commented on test/JDBC/expected/BABEL-3486-vu-verify.out
> +2017-08-25 13:01:59.1234570
Can you verify that this rounding behavior is correct? Just to be careful.

2022-10-26 16:34 UTC, timchang514 commented on test/JDBC/input/BABEL-3614-vu-prepare.sql
> +CREATE VIEW BABEL_3614_vu_prepare_v1 as (SELECT TRY_CONVERT(DATETIME2(5), '2017-08-25 13:01:10.1234567'));
Can you add some tests that check the entire range of datetime2? i.e. dates between 0001 and 1753?

2022-10-28 16:10 UTC, AvantikaDG submitted a review, later dismissed

2022-10-28 16:33 UTC, AvantikaDG approved these changes

2022-10-28 18:35 UTC, timchang514 approved these changes

2022-10-31 16:41 UTC, merged