Disallow ALTER ROLE in PG for Babelfish-created roles
babelfish-for-postgresql/babelfish_extensions pull request #721
Opened 2022-10-24 18:42 UTC by Suthapalli-Ramya-satya-vasavi-srija

Previously, for a PG user to break a Babelfish instance by using ALTER ROLE to block logins, change role membership, change passwords, and other changes that would have a dramatic effect on Babelfish functionality. Now, ALTER ROLE been disabled for Babelfish-created PG roles.

Task: Babel-2976
Signed-off-by: vasavi suthapalli <svasusri@amazon.com>

### Description

[Describe what this change achieves]
 
### Issues Resolved

[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-24 19:01 UTC, xhfanhe commented
Please add test to upgrade schdules

2022-10-24 19:03 UTC, xhfanhe commented
This test doesn't need to be an upgrade test.

2022-10-26 03:11 UTC, shalinilohia50 commented
Please add test template to the PR description.

2022-10-26 06:36 UTC, HarshLunagariya requested changes

2022-10-26 06:36 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +    name = NULL;
We can remove this line. No need to assign NULL.

2022-10-26 06:36 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +    name = NULL;
We can remove this line. No need to assign NULL.

2022-10-26 06:36 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +			break;
Is this change needed now? Won't it be handled by OAT_POST_ALTER case in object_access_hook?

2022-10-26 14:04 UTC, shalinilohia50 commented on test/JDBC/input/ownership-restrictions-from-pg.mix
> +CREATE ROLE r4;
I think adding file names as prefixes to the names would be better and helpful in debugging the issues later(if any).

2022-10-26 15:10 UTC, Suthapalli-Ramya-satya-vasavi-srija commented on test/JDBC/input/ownership-restrictions-from-pg.mix
> +CREATE ROLE r4;
Fixed in next revision by adding file name as prefixes for role/user/login names.

2022-10-26 16:13 UTC, xhfanhe approved these changes

2022-10-26 16:14 UTC, merged