Fix warnings which is occuring during compilation of babel
babelfish-for-postgresql/babelfish_extensions pull request #943
Opened 2022-12-15 09:03 UTC by sumitj824

### Description

So far we were  getting lots of warning during compilation of babel. This commit fix warnings which were occurring during compilation of babel and add flags so that warnings will be treated as errors. 
 
Engine PR :
### Issues Resolved

[BABEL-3666]

Signed-off-by: Sumit Jaiswal <sumiji@amazon.com>

### Testing
We don't need to add more tests as we already have test coverage for functions which are getting modified in this commit to fix the warnings in them. Also these changes has been verified by the corresponding author.
* **Use case based -**
 NA

* **Boundary conditions -**
  NA

* **Arbitrary inputs -**
  NA

* **Negative test cases -**
  NA

* **Minor version upgrade tests -**
 NA

* **Major version upgrade tests -**
 NA

* **Performance tests -**
  NA

* **Tooling impact -**
   NA

* **Client tests -**
  JDBC, ODBC, .NET, Python drivers

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-15 11:37 UTC, Deepesh125 requested changes

2022-12-15 11:37 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/plerrcodes.h
> +
check this diff

2022-12-15 11:37 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pltsql_ruleutils.c
> +
remove this space

2022-12-15 11:37 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pltsql_ruleutils.c
> +	 */
remove extra spaces

2022-12-15 11:58 UTC, sumitj824 commented on contrib/babelfishpg_tsql/src/plerrcodes.h
> +
removed

2022-12-15 11:59 UTC, sumitj824 commented on contrib/babelfishpg_tsql/src/pltsql_ruleutils.c
> +
removed

2022-12-15 12:00 UTC, sumitj824 commented on contrib/babelfishpg_tsql/src/pltsql_ruleutils.c
> +	 */
there isn't any extra spaces

2022-12-16 04:19 UTC, Deepesh125 approved these changes

2022-12-16 04:20 UTC, merged