Support T-SQL Linked Servers
babelfish-for-postgresql/babelfish_extensions pull request #944
Opened 2022-12-15 13:32 UTC by thephantomthief

### Description

This commit adds the support for T-SQL linked server objects through
PostgreSQL foreign data wrappers (FDWs). Currently, only support for
linked servers for remote SQL Servers is added. Thus, to add linked
servers of this type, the tds_fdw extension needs to be installed.

Also, added the support for T-SQL sp_addlinkedserver stored procedure to
add a linked server in Babelfish and sys.servers system view to show
list of linked servers.

sp_addlinkedserver stored procedure has been implemented such that
internally it uses PG's CREATE FOREIGN SERVER logic and so, a linked
server added is internally a PG foreign server. sys.servers system view
uses the pg_foreign_server catalog internally.

Task: BABEL-861
Signed-off-by: Sharu Goel <goelshar@amazon.com>

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** N/A

* **Arbitrary inputs -** N/A

* **Negative test cases -** Yes

* **Minor version upgrade tests -** N/A

* **Major version upgrade tests -** N/A

* **Performance tests -** N/A

* **Tooling impact -** Yes

* **Client tests -** N/A

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-27 05:35 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/procedures.c
> +create_linked_server_procs_in_master_dbo_internal(PG_FUNCTION_ARGS)
Can you please explain why we have created a C type function to create another function?
>  CALL sys.create_linked_server_procs_in_master_dbo();
  ALTER PROCEDURE master_dbo.sp_addlinkedserver OWNER TO sysadmin;
  DROP PROCEDURE sys.create_linked_server_procs_in_master_dbo;

The above logic seems counter intuitive and kind of confusing to understand the need for sys.create_linked_server_procs_in_master_dbo

2022-12-27 05:35 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/procedures.c
> +	const char  *dbo_scm = get_dbo_schema_name("master");
In ownership.sql you have blindly used master_dbo, where as here we are relying on an API, can you please explain why we need that? If so why arent we doing something similar in .sql?

2022-12-27 05:35 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/procedures.c
> +	List *options = NIL;
We should free all the pointers/lists

2022-12-27 05:35 UTC, KushaalShroff commented on contrib/babelfishpg_tsql/src/procedures.c
> +ValidateLinkedServerDataSource(char* data_src)
Do we really need a function for this?
We can use a macro instead. Moreover, we are using it only once so I dont see a point.

2023-01-06 06:19 UTC, Deepesh125 requested changes

2023-01-06 06:19 UTC, Deepesh125 commented on .github/composite-actions/setup-base-version/action.yml
> +      shell: bash
are these steps same as composite-actions/build-tds_fdw-extension? if so can we utilise the same here? and possibly at other places?

2023-01-06 06:19 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +  CAST('tds_fdw' as sys.sysname) AS provider,
From T-sql documentation - `The value in provider_string is always NULL unless the caller has the ALTER ANY LINKED SERVER permission.`

2023-01-06 06:19 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/procedures.c
> +	/* Add the relevant options */
Please add comment with more info, give an example how options would look like with final query string?

2023-01-06 06:19 UTC, Deepesh125 commented on test/python/expected/upgrade_validation/expected_dependency.out
> +View sys.servers
let's add dependency test cases for sys.servers

2023-01-06 06:44 UTC, thephantomthief commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--3.0.0--3.1.0.sql
> +  CAST('tds_fdw' as sys.sysname) AS provider,
provider is different from provider string

2023-01-06 06:46 UTC, thephantomthief commented on .github/composite-actions/setup-base-version/action.yml
> +      shell: bash
at places where we checkout older branches, we cannot reuse the composite action

2023-01-06 10:28 UTC, Deepesh125 approved these changes

2023-01-06 12:23 UTC, kuntalghosh approved these changes

2023-01-09 06:46 UTC, merged